package serie4;

public final class Musikerdaten {

	/**
	 * Die statische Funktion gibt die Informationen zu den Musikern zurueck.
	 * Fuer jedes Feld entsprechen die ersten 8 Elemente dem gleichen Informationstyp.
	 * Element 1: Name
	 * Element 2: Geschlecht
	 * Element 3: Geburtsjahr   
	 * Element 4: Sterbejahr
	 * Element 5: Musikalische Berufe (separiert mit '#')
	 * Element 6: Nicht-musikalische Berufe (separiert mit '#')
	 * Element 7: Wirkungsorte (separiert mit '#')
	 * 
	 * HINWEIS: Zum "Auftrennen" der Wirkungsorte, musikalischen und nicht-musikalischen Berufe in einzelne Elemente (Strings) suchen sie eine passende Methode der Klasse String aus der Java API heraus.
	 * siehe https://docs.oracle.com/javase/8/docs/api/
	 * 
	 * @return Biografische Daten zu Musikern
	 */
	public static String[][] getMusiker(){
		return new String[][]{
				{"Mozart, Wolfgang Amadeus","m","1756","1791","Komponist#Kapellmeister#Konzertmeister#Pianist#Organist#Geiger#Sänger","","Amsterdam#Berlin#Bologna#Frankfurt/Main#London#Mailand#Mannheim#München#Paris#Potsdam#Prag#Wallerstein#Salzburg#Wien"},
				{"Bach, Johann Sebastian","m","1685","1750","Komponist#Organist#Chorleiter#Dirigent#Kapellmeister#Klavierlehrer#Cembalist#Kompositionslehrer#Musikpädagoge","Lehrer","Hamburg#Lübeck#Lüneburg#Mühlhausen/Thüringen#Potsdam#Weimar#Leipzig"},
				{"Luther, Martin","m","1483","1546","Komponist#Musikdokumentar#Sänger#Lautenist#Chorknabe","Geistlicher#Theologe#Professor#Pfarrer#Schriftsteller","Augsburg#Coburg#Erfurt#Magdeburg#Wittenberg"},
				{"Beethoven, Ludwig van","m","1770","1827","Komponist#Pianist#Organist#Bratscher","","Aschaffenburg#Berlin#Bonn#Dresden#Karlsbad#Koblenz#Köln#Linz#Nürnberg#Prag#Troppau#Wallerstein#Wien"},
				{"Haydn, Joseph","m","1732","1809","Komponist#Kapellmeister#Chorleiter#Dirigent#Organist#Pianist#Geiger#Musikpädagoge#Instrumentalist#Sänger#Chorknabe","Diener","Bonn#Bratislava#Brüssel#Budapest#Coburg#Dresden#Eisenstadt#Fertöd#Frankfurt/Main#Graz#Hamburg#London#München#Passau#Schärding#Wallerstein#Wien#Wiesbaden"},
				{"Schubert, Franz","m","1797","1828","Komponist#Pianist#Musikpädagoge#Sänger#Chorknabe","Lehrer","Linz#Wien"},
				{"Händel, Georg Friedrich","m","1685","1759","Komponist#Kapellmeister#Organist#Geiger#Cembalist","","Hamburg#Hannover#Lübeck#Neapel#Rom#Venedig#London"},
				{"Brahms, Johannes","m","1833","1897","Komponist#Pianist#Dirigent#Chorleiter#Textdichter#Bearbeiter","","Bonn#Breslau#Dänemark#Düsseldorf#Göttingen#Hamburg#Hannover#Italien#Karlsbad#Leipzig#Lüneburg#Niederlande#Österreich#Schweiz#Ungarn#Weimar#Wien#Wiesbaden"},
				{"Wagner, Richard","m","1813","1883","Komponist#Musikschriftsteller#Textdichter#Dirigent#Kapellmeister#Chorleiter#Pianist","Schriftsteller#Regisseur#Intendant","Bad Reichenhall#Bayreuth#Breslau#Budapest#Dresden#Frankfurt/Main#Hannover#Karlsruhe#Königsberg#Leipzig#London#Luzern#Magdeburg#Moskau#München#Neapel#Nürnberg#Palermo#Paris#Prag#Riga#St. Petersburg#Starnberg#Venedig#Weimar#Wien#Würzburg#Zürich"},
				{"Schumann, Robert","m","1810","1856","Pianist#Komponist","Journalist#Jurist","Bayreuth#Berlin#Bonn#Dresden#Düsseldorf#Frankfurt/Main#Hamburg#Heidelberg#Karlsbad#Köln#Kreischa#Leipzig#Mailand#Moskau#München#St. Petersburg#Wien#Zwickau"},
				{"Strauss, Richard","m","1864","1949","Komponist#Dirigent#Kapellmeister#Pianist#Geiger#Kompositionslehrer","","Amsterdam#Argentinien#Athen#Barcelona#Bayreuth#Berlin#Brasilien#Braunschweig#Brüssel#Budapest#Dresden#Düsseldorf#Edinburgh#Feldafing#Frankfurt/Main#Garmisch-Partenkirchen#Hamburg#Heidelberg#Italien#Köln#Krefeld#Lausanne#Leipzig#Lemberg#London#Madrid#Mailand#Meiningen#Moskau#New York#Palermo#Paris#Philadelphia#Portugal#Prag#Salzburg#Warschau#Weimar#Wien#Würzburg#München"},
				{"Liszt, Franz","m","1811","1886","Pianist#Komponist#Bearbeiter#Klavierlehrer#Kapellmeister#Dirigent","","Aachen#Bayreuth#Berlin#Bonn#Bratislava#Brüssel#Budapest#England#Erfurt#Frankreich#Genf#Hamburg#Italien#Königsberg#Kopenhagen#Leipzig#London#Luxemburg#Marburg#München#Paris#Portugal#Prag#Rom#Schlesien#Schottland#Schweiz#Sondershausen#Sopron#Spanien#St. Petersburg#Venedig#Wien#Wiesbaden#Weimar"},
				{"Mendelssohn Bartholdy, Felix","m","1809","1847","Komponist#Dirigent#Chorleiter#Pianist#Bearbeiter#Musikpädagoge","","Augsburg#Berlin#Düsseldorf#Florenz#Frankfurt/Main#Genf#Genua#Graz#Heidelberg#Köln#Leipzig#Linz#London#Luzern#Mailand#München#Neapel#Paris#Potsdam#Rom#Schottland#St. Gallen#Stettin#Stuttgart#Venedig#Weimar#Wien"},
				{"Telemann, Georg Philipp","m","1681","1767","Komponist#Dirigent#Kapellmeister#Konzertmeister#Chorleiter#Organist#Musikpädagoge#Geiger#Flötist#Zitherspieler#Instrumentalist#Musikdokumentar#Musikverleger#Musikschriftsteller","","Bayreuth#Berlin#Braunschweig#Dresden#Frankfurt/Main#Frankfurt/Oder#Halle#Hannover#Krakau#Leipzig#Magdeburg#Paris#Wolfenbüttel#Hamburg"},
				{"Melanchthon, Philipp","m","1497","1560","Komponist#Musikschriftsteller","Schriftsteller#Theologe#Philologe#Lehrer","Augsburg#Heidelberg#Pforzheim#Tübingen#Wittenberg"},
				{"Chopin, Frédéric","m","1810","1849","Komponist#Pianist#Klavierlehrer#Organist","","Aachen#Berlin#Breslau#Dresden#Düsseldorf#Edinburgh#Karlsbad#Leipzig#London#München#Prag#Salzburg#Stuttgart#Warschau#Wien#Paris"},
				{"Vivaldi, Antonio","m","1678","1741","Komponist#Geiger#Geigenlehrer#Konzertmeister#Cembalist","Pfarrer","Prag#Rom#Venedig#Verona#Wien"},
				{"Augustinus, Aurelius","m","0354","0430","Musikschriftsteller","Bischof#Schriftsteller","Mailand#Rom"},
				{"Cajkovskij, Petr I.","m","1840","1893","Komponist#Dirigent#Musikpädagoge#Kompositionslehrer#Musikredakteur","Jurist","Bayreuth#Berlin#Florenz#Hamburg#Leipzig#London#Moskau#New York#Österreich#Paris#Prag#Rom#Schweiz#St. Petersburg"},
				{"Brecht, Bertolt","m","1898","1956","Textdichter#Komponist#Sänger#Unterhaltungskünstler","Schriftsteller#Regisseur#Schauspieler#Geisteswissenschaftler","Augsburg#Berlin#Dänemark#Finnland#Frankreich#München#Österreich#Schweden#Schweiz#USA"},
				{"Friedrich (6)","m","1712","1786","Flötist#Komponist","König#Kurfürst#Schriftsteller","Berlin#Dresden#Potsdam"},
				{"Mann, Thomas","m","1875","1955","Musikschriftsteller#Pianist#Geiger","Schriftsteller#Professor","Italien#München"},
				{"Rossini, Gioacchino","m","1792","1868","Komponist#Sänger#Geiger#Violoncellist#Pianist#Musiktheaterregisseur","Intendant","Bologna#Florenz#London#Neapel#Rom#Paris"},
				{"Nietzsche, Friedrich Wilhelm","m","1844","1900","Pianist#Komponist","Philosoph#Philologe#Schriftsteller#Professor#Kulturwissenschaftler","Basel#Luzern"},
				{"Lessing, Gotthold Ephraim","m","1729","1781","Textdichter","Dichter#Schriftsteller#Bibliothekar","Berlin#Breslau#Dresden#England#Florenz#Frankreich#Genua#Hamburg#Leipzig#Mailand#Neapel#Niederlande#Prag#Rom#Turin#Venedig#Wien#Wittenberg#Wolfenbüttel"},
				{"Weber, Carl Maria von","m","1786","1826","Komponist#Pianist#Dirigent","Schriftsteller","Augsburg#Bamberg#Berlin#Breslau#Darmstadt#Dresden#Frankfurt/Main#Freiberg#Heidelberg#Hildburghausen#Karlsbad#Leipzig#London#Ludwigsburg#Mannheim#München#Oberfranken#Paris#Prag#Salzburg#Schweiz#Starnberg#Stuttgart#Weimar#Wien"},
				{"Reger, Max","m","1873","1916","Komponist#Organist#Pianist#Musikpädagoge#Kompositionslehrer#Orgellehrer#Klavierlehrer#Bearbeiter#Musikschriftsteller#Musikforscher","","Bayreuth#Bologna#Jena#Leipzig#London#Meiningen#Meran#München#Sondershausen#Tutzing#Venedig#Weiden#Wiesbaden"},
				{"Debussy, Claude","m","1862","1918","Komponist#Pianist#Dirigent#Klavierlehrer#Musikpädagoge#Musikredakteur#Bearbeiter","","Bayreuth#Brüssel#Budapest#London#Moskau#Niederlande#Rom#Schweiz#St. Petersburg#Turin#Venedig#Wien#Paris"},
				{"Hesse, Hermann","m","1877","1962","Textdichter#Musikliebhaber","Dichter#Schriftsteller#Maler#Buchhändler","Basel#Bern#Bologna#Florenz#Genua#Mailand#Padua#Stuttgart#Tübingen#Venedig"},
				{"Rilke, Rainer Maria","m","1875","1926","Textdichter#Musikschriftsteller","","Bad Aussee#Berlin#Florenz#Linz#München#Paris#Prag#Russland#Spanien#Wien"},
				{"Dvořák, Antonín","m","1841","1904","Komponist#Organist#Dirigent#Geiger#Bratscher#Pianist#Klavierlehrer","Professor","London#Moskau#Nelahozeves#New York#Prag#St. Petersburg#Wien"},
				{"Bach, Carl Philipp Emanuel","m","1714","1788","Komponist#Cembalist#Organist#Dirigent#Musikverleger#Musikpädagoge","","Berlin#Frankfurt/Oder#Hamburg#Leipzig"},
				{"Strawinsky, Igor Fjodorowitsch","m","1882","1971","Komponist#Dirigent#Pianist","Jurist#Professor","Donaueschingen#Genf#New York#Paris#Schweiz#St. Petersburg#Venedig"},
				{"Hoffmann, Ernst T. A.","m","1776","1822","Komponist#Pianist#Sänger#Musikpädagoge#Musikalischer Leiter","Schriftsteller#Maler#Jurist","Bamberg#Berlin#Dresden#Königsberg#Leipzig#Warschau"},
				{"Hegel, Georg Wilhelm Friedrich","m","1770","1831","Musikschriftsteller","Philosoph#Theologe#Lehrer","Bamberg#Berlin#Bern#Frankfurt/Main#Heidelberg#Jena#Nürnberg#Tübingen"},
				{"Haydn, Michael","m","1737","1806","Komponist#Kapellmeister#Dirigent#Konzertmeister#Organist#Geiger#Musikpädagoge#Geigenlehrer#Tenor#Harfenist","","Augsburg#Bratislava#Eisenstadt#Linz#Wien#Salzburg"},
				{"Strauss, Johann","m","1825","1899","Komponist#Kapellmeister#Dirigent#Geiger","","USA#Coburg#Wien"},
				{"Mahler, Gustav","m","1860","1911","Komponist#Dirigent#Kapellmeister#Pianist#Bearbeiter","Intendant","Budapest#Hamburg#Kassel#Leipzig#Ljubljana#London#Moskau#München#New York#Paris#Polen#Prag#Wien"},
				{"Bartók, Béla Viktor János","m","1881","1945","Komponist#Volksliedsammler","","Bratislava#Budapest#USA"},
				{"Palestrina, Pierluigi da","m","1525","1594","Komponist#Dirigent#Kapellmeister#Sänger","","Rom"},
				{"Hindemith, Paul","m","1895","1963","Komponist#Dirigent#Pianist#Geiger#Bratscher#Kompositionslehrer","Professor","Baden-Baden#Bayreuth#Berlin#Donaueschingen#Frankfurt/Main#Hamburg#Japan#Kanada#Perugia#Rom#Wien#Zürich"},
				{"Hölderlin, Friedrich","m","1770","1843","Textdichter","Dichter#Schriftsteller#Bibliothekar#Lehrer","Jena#Tübingen"},
				{"Rousseau, Jean Jacques","m","1712","1778","Komponist#Musikschriftsteller","Philosoph#Schriftsteller#Pädagoge","England#Genf#Lyon#Paris"},
				{"Bruckner, Anton","m","1824","1896","Komponist#Dirigent#Chorleiter#Organist#Pianist#Musikpädagoge#Orgellehrer#Kompositionslehrer#Chorknabe","Lehrer#Professor","Bayreuth#Berlin#Krems#Leipzig#Linz#London#Mannheim#München#Nancy#Nürnberg#Oberammergau#Paris#Salzburg#Schweiz#Wien"},
				{"Prokofjew, Sergei Sergejewitsch","m","1891","1953","Komponist#Pianist","","Ettal#Moskau#Paris#USA"},
				{"Dürer, Albrecht","m","1471","1528","Komponist","Maler#Kunstwissenschaftler#Schriftsteller#Mathematiker","Nürnberg"},
				{"Herder, Johann Gottfried von","m","1744","1803","Volksliedsammler#Herausgeber#Musikschriftsteller#Textdichter","Schriftsteller#Dichter#Philosoph#Übersetzer#Theologe#Schulleiter#Pfarrer","Darmstadt#Königsberg#Mannheim#Paris#Riga#Straßburg#Weimar"},
				{"Schönberg, Arnold","m","1874","1951","Komponist#Kompositionslehrer#Musikschriftsteller#Pianist#Dirigent#Geiger#Violoncellist#Chorleiter#Textdichter#Bearbeiter","Bankkaufmann#Beamter#Maler","Amsterdam#Barcelona#Berlin#Chicago#Frankreich#München#New York#Wien"},
				{"Schütz, Heinrich","m","1585","1672","Komponist#Kapellmeister#Dirigent#Organist#Musikpädagoge#Diskantist#Chorknabe","","Amsterdam#Bayreuth#Breslau#Frankfurt/Oder#Hamburg#Hannover#Jena#Kassel#Kopenhagen#Leipzig#Marburg#Venedig#Weimar#Weißenfels#Wolfenbüttel#Dresden"},
				{"Grieg, Edvard","m","1843","1907","Komponist#Pianist","","Amsterdam#Bayreuth#Berlin#Budapest#Kiel#Kopenhagen#Leipzig#München#Paris#Prag#Rom#Stockholm#Warschau#Weimar#Wien"},
				{"Vinci, Leonardo da","m","1452","1519","Musiker","Architekt#Maler#Ingenieur","Florenz#Mailand#Rom#Venedig"},
				{"Zweig, Stefan","m","1881","1942","Textdichter#Musikaliensammler","Schriftsteller","Berlin#Brasilien#London#Wien"},
				{"Eichendorff, Joseph Karl Benedikt Freiherr von","m","1788","1857","Textdichter","Schriftsteller#Adliger#Jurist#Soldat#Übersetzer","Breslau#Dresden#Halle#Hamburg#Heidelberg#Karlsbad#Königsberg#Linz#Lübeck#Nürnberg#Paris#Prag#Regensburg#Straßburg#Wien#Würzburg"},
				{"Leibniz, Gottfried Wilhelm","m","1646","1716","Musikschriftsteller","Philosoph#Mathematiker#Physiker#Historiker#Bibliothekar#Politiker#Schriftsteller#Gelehrter","Altdorf#Hannover#Italien#Jena#Leipzig#Nürnberg#Paris"},
				{"Gluck, Christoph Willibald von","m","1714","1787","Komponist#Dirigent#Kapellmeister#Konzertmeister#Cembalist#Instrumentalist#Sänger","Ritter#Intendant","Berlin#Bologna#Dresden#Florenz#Frankfurt/Main#Hamburg#Karlsruhe#Kopenhagen#London#Mailand#Moskau#Neapel#Paris#Parma#Prag#Rastatt#Regensburg#Rom#Turin#Venedig#Wien"},
				{"Stifter, Adalbert","m","1805","1868","Textdichter#Sänger","Schriftsteller#Maler#Lehrer","Wien"},
				{"Rheinberger, Joseph","m","1839","1901","Komponist#Musikpädagoge#Orgellehrer#Pianist#Organist#Dirigent#Kapellmeister#Chorleiter","Professor#Rat","München"},
				{"Lasso, Orlando di","m","1532","1594","Komponist#Kapellmeister#Dirigent#Musikpädagoge#Gesangslehrer#Sänger#Lautenist#Diskantist#Chorknabe","Schauspieler","Altötting#Augsburg#Bologna#Florenz#Frankfurt/Main#Freising#Genua#Loreto#Mailand#Neapel#Niederlande#Nürnberg#Palermo#Paris#Prag#Regensburg#Rom#Venedig#Verona#Wien#München"},
				{"Adorno, Theodor Wiesengrund","m","1903","1969","Musiksoziologe#Komponist#Pianist#Musikforscher#Musikredakteur","Philosoph#Soziologe#Professor","Wien#Frankfurt/Main"},
				{"Saint-Saëns, Camille","m","1835","1921","Komponist#Pianist#Organist#Dirigent#Musikschriftsteller","","München#USA#Paris"},
				{"Richter, Jean Paul Friedrich","m","1763","1825","Komponist#Textdichter","Schriftsteller","Bamberg#Berlin#Coburg#Dresden#Frankfurt/Main#Heidelberg#Leipzig#Mannheim#Meiningen#München#Stuttgart#Weimar#Bayreuth"},
				{"Wolf, Hugo","m","1860","1903","Komponist#Chorleiter#Dirigent#Kapellmeister#Musikredakteur#Geiger#Pianist#Organist#Sänger#Geigenlehrer#Klavierlehrer","","Bayreuth#Berlin#Darmstadt#Graz#Köln#Mainz#Mannheim#München#Salzburg#Stuttgart#Tübingen#Wien"},
				{"Tieck, Ludwig","m","1773","1853","Textdichter#Musikforscher#Musikschriftsteller#Komponist","Schriftsteller#Schauspieler#Übersetzer","Bayreuth#Berlin#Erlangen#Halle#Jena#London#München#Nürnberg#Prag#Rom#Wien#Dresden"},
				{"Kästner, Erich","m","1899","1974","Unterhaltungskünstler","Schriftsteller","Berlin#Leipzig#München#Tirol"},
				{"Hasse, Johann Adolf","m","1699","1783","Komponist#Kapellmeister#Tenor#Musikpädagoge","","Bayreuth#Berlin#Bologna#Braunschweig#Florenz#Hamburg#Leipzig#Mailand#München#Neapel#Paris#Potsdam#Rom#Turin#Venedig#Warschau#Wien#Dresden"},
				{"Monteverdi, Claudio Zuan Antonio","m","1567","1643","Komponist#Kapellmeister#Dirigent#Sänger#Bratscher","Pfarrer","Brüssel#Cremona#Venedig"},
				{"Fischer-Dieskau, Dietrich","m","1925","2012","Bariton#Dirigent#Musikforscher#Gesangslehrer","Schauspieler#Soldat","Bayreuth#Berlin#Edinburgh#Freiburg/Breisgau#Glyndebourne#Leipzig#London#Luzern#Mailand#München#New York#Salzburg#Schwetzingen#Wien"},
				{"Spohr, Louis","m","1784","1859","Geiger#Organist#Komponist#Dirigent#Konzertmeister#Geigenlehrer#Veranstalter","","Belgien#Braunschweig#Dresden#Frankfurt/Main#Italien#Kassel#London#München#Niederlande#Paris#Schweiz#Wien"},
				{"Fauré, Gabriel","m","1845","1924","Komponist#Organist#Kompositionslehrer","Professor#Schulleiter","Barcelona#Bayreuth#Berlin#Brüssel#Frankfurt/Main#Köln#Lausanne#London#Moskau#Paris#St. Petersburg#Venedig"},
				{"Brentano, Clemens","m","1778","1842","Textdichter","Schriftsteller","Berlin#Göttingen#Halle#Heidelberg#Jena#Landshut#München#Prag#Wien"},
				{"Busch, Wilhelm","m","1832","1908","Textdichter","Dichter#Maler#Ingenieur","Düsseldorf#Frankfurt/Main#Hannover#München"},
				{"Pleyel, Ignatz","m","1757","1831","Komponist#Musikverleger#Musikalienhändler#Klavierbauer#Pianist#Organist#Musikpädagoge","","Bratislava#Eisenstadt#Italien#London#Straßburg#Paris"},
				{"Scarlatti, Pietro Alessandro Gaspare","m","1660","1725","Komponist#Kapellmeister#Dirigent","","Florenz#Loreto#Neapel#Rom"},
				{"Bernstein, Leonard","m","1918","1990","Dirigent#Komponist#Pianist#Musikpädagoge#Musikschriftsteller","","Berlin#Brüssel#Israel#London#Mailand#München#New York#Paris#Philadelphia#Prag#Wien"},
				{"Meyerbeer, Giacomo","m","1791","1864","Komponist#Pianist","","Berlin#Darmstadt#Italien#London#München#Paris"},
				{"Mann, Heinrich","m","1871","1950","","Schriftsteller","Berlin#Dresden#Lausanne#Lübeck#München#Portugal#Spanien#USA#Wiesbaden"},
				{"Weber, Max","m","1864","1920","Musiksoziologe","Soziologe#Kulturwissenschaftler#Jurist#Professor#Schriftsteller#Offizier","Berlin#Freiburg/Breisgau#Heidelberg#München#Straßburg#Wien"},
				{"Descartes, René","m","1596","1650","Musikschriftsteller","Mathematiker#Philosoph#Jurist","Belgien#Frankfurt/Main#Italien#Paris#Prag#Schweiz#Stockholm#Ulm#Ungarn#Wien"},
				{"Bach, Johann Christian","m","1735","1782","Komponist#Cembalist#Organist#Kapellmeister#Dirigent","","Berlin#Bologna#Leipzig#London#Mailand#Paris"},
				{"Janáček, Leoš","m","1854","1928","Komponist#Chorleiter#Dirigent#Pianist#Organist#Klavierlehrer#Kompositionslehrer#Musikschriftsteller","Schulleiter#Professor","Leipzig#Prag#Wien#Brünn"},
				{"Mussorgskij, Modest Petrowitsch","m","1839","1881","Komponist#Pianist#Musikpädagoge","","Krim#Moskau#St. Petersburg"},
				{"Loewe, Carl","m","1796","1869","Komponist#Organist#Pianist#Dirigent#Musikpädagoge#Tenor#Sopranist#Chorknabe","","Berlin#Greifswald#Halle#Stettin"},
				{"Corelli, Arcangelo","m","1653","1713","Komponist#Dirigent#Konzertmeister#Geiger#Geigenlehrer#Musikaliensammler","Archivar#Kunstwissenschaftler","Bologna#Neapel#Rom"},
				{"Karajan, Herbert von","m","1908","1989","Dirigent#Kapellmeister#Pianist","Regisseur","Aachen#Bayreuth#Berlin#London#Luzern#Mailand#Paris#Salzburg#Ulm#Wien"},
				{"Henze, Hans Werner","m","1926","2012","Dirigent#Komponist#Textdichter#Pianist#Musikpädagoge#Schlagzeuger#Korrepetitor#Leitungsperson","Ritter#Politiker#Soldat","Berlin#Bielefeld#Braunschweig#Darmstadt#Heidelberg#Köln#Konstanz#München#Neapel#Paris#Rom#Wiesbaden"},
				{"Pfitzner, Hans","m","1869","1949","Komponist#Dirigent#Kapellmeister#Pianist#Musikpädagoge#Kompositionslehrer#Klavierlehrer#Musikdokumentar#Textdichter","Regisseur","Berlin#Frankfurt/Main#Garmisch-Partenkirchen#Koblenz#Mainz#München#Salzburg#Schondorf/Ammersee#Straßburg#Wien#Wiesbaden#Wuppertal"},
				{"Paisiello, Giovanni","m","1740","1816","Komponist#Kapellmeister","","Bologna#Graz#Neapel#Paris#Parma#Venedig#Wien"},
				{"Berg, Alban Maria Johannes","m","1885","1935","Komponist#Pianist#Kompositionslehrer","","Berlin#Frankfurt/Main#Wien"},
				{"Stockhausen, Karlheinz","m","1928","2007","Komponist#Dirigent#Pianist#Musikpädagoge","Professor","Köln#München"},
				{"Friedrich Wilhelm (2)","m","1688","1740","Musikliebhaber","König#Markgraf#Kurfürst","Berlin#Halle#Hannover#Niederlande"},
				{"Schelling, Friedrich Wilhelm Joseph von","m","1775","1854","Musikschriftsteller","Philosoph#Professor","Berlin#Erlangen#Jena#Leipzig#München#Tübingen#Würzburg"},
				{"Cherubini, Luigi","m","1760","1842","Komponist","","Paris#Turin"},
				{"Messiaen, Olivier","m","1908","1992","Komponist#Organist#Pianist#Musikpädagoge#Musikforscher","","Australien#Budapest#Buenos Aires#Darmstadt#Donaueschingen#Israel#Japan#Moosburg#München#Saarbrücken#Venedig#Paris"},
				{"Scarlatti, Giuseppe Domenico","m","1685","1757","Komponist#Cembalist#Organist","","Lissabon#Madrid#Neapel#Rom#Venedig"},
				{"Sachs, Hans","m","1494","1576","Meistersinger#Sänger#Textdichter#Komponist","Handwerker#Jäger#Schriftsteller#Lehrer","Aachen#Braunau/Inn#Burghausen#Frankfurt/Main#Hall/Tirol#Innsbruck#Koblenz#Landshut#München#Niedersachsen#Passau#Regensburg#Sachsen#Salzburg#Wien#Würzburg#Nürnberg"},
				{"Rückert, Friedrich","m","1788","1866","Textdichter","Schriftsteller#Jurist#Philologe","Berlin#Erlangen#Göttingen#Heidelberg#Jena#Rom#Schweiz#Wien#Würzburg"},
				{"Hummel, Johann Nepomuk","m","1778","1837","Pianist#Komponist#Kapellmeister#Dirigent","","Belgien#Berlin#Dessau#Dresden#Eisenstadt#Kopenhagen#London#Moskau#München#Niederlande#Paris#Prag#Schottland#St. Petersburg#Stuttgart#Warschau#Wien#Weimar"},
				{"Lortzing, Albert","m","1801","1851","Komponist#Bearbeiter#Dirigent#Kapellmeister#Tenor#Pianist#Geiger#Violoncellist#Kopist","Schauspieler#Schriftsteller","Aachen#Baden-Baden#Bamberg#Berlin#Bonn#Breslau#Coburg#Detmold#Düsseldorf#Freiburg/Breisgau#Hamburg#Köln#Münster#Weimar#Wien#Wuppertal#Leipzig"},
				{"Wolfram","m","1170","1220","Minnesänger#Sänger","Schriftsteller#Adliger","Wertheim#Markt Erlbach"},
				{"Heyse, Paul","m","1830","1914","Textdichter","Schriftsteller#Philologe#Professor","Berlin#Bonn#Italien#München"},
				{"Schmid, Christoph von","m","1768","1854","Komponist","Pfarrer#Schriftsteller#Lehrer","Augsburg#Dillingen/Donau#Mindelheim#Thannhausen"},
				{"Webern, Anton von","m","1883","1945","Komponist#Dirigent#Kapellmeister#Korrepetitor#Musikforscher#Chorleiter#Musikpädagoge","","Düsseldorf#Graz#Klagenfurt#London#Mittersill#Prag#Stettin#Winterthur#Wien"},
				{"Elgar, Edward","m","1857","1934","Komponist#Dirigent#Chorleiter#Konzertmeister#Organist#Pianist#Geiger#Fagottist#Musikpädagoge#Geigenlehrer","Ritter","Bayreuth#Düsseldorf#Garmisch-Partenkirchen#Italien#Leipzig#London#München#USA"},
				{"Pergolesi, Giambattista","m","1710","1736","Komponist","","Graz#Neapel"},
				{"Paganini, Niccolò","m","1782","1840","Geiger#Komponist#Gitarrist","","Augsburg#Berlin#Frankfurt/Main#Kassel#London#Mailand#München#Nürnberg#Paris#Parma#Prag#Weimar#Wien"},
				{"Lully, Jean-Baptiste","m","1632","1687","Komponist#Geiger#Tänzer#Cembalist#Gitarrist#Musiktheaterintendant","Schauspieler#Diener#Adliger#Lehrer","Florenz#Versailles#Paris"},
				{"Milhaud, Darius","m","1892","1974","Komponist#Dirigent#Geiger#Musikschriftsteller","Professor","Baden-Baden#Berlin#Chicago#Lissabon#Lyon#Madrid#München#New York#Paris#Wiesbaden"},
				{"Da Ponte, Lorenzo","m","1749","1838","Textdichter#Musikalienhändler","Geistlicher#Pfarrer#Schriftsteller#Lehrer#Buchhändler#Händler#Unternehmer#Intendant","Dresden#London#New York#Niederlande#Philadelphia#Prag#Triest#Venedig#Wien"},
				{"Albertus Magnus","m","1193","1280","Musikdokumentar#Komponist#Musikpädagoge","Geistlicher#Lehrer#Theologe#Mönch#Bischof#Philosoph#Naturwissenschaftler","Freiburg/Breisgau#Köln#Lyon#Padua#Paris#Regensburg#Straßburg#Tschechien#Würzburg"},
				{"Cimarosa, Domenico","m","1749","1801","Komponist#Kapellmeister#Dirigent#Organist","","Florenz#Mailand#Neapel#Rom#St. Petersburg#Venedig"},
				{"Rolland, Romain","m","1866","1944","Musikforscher#Musikkritiker","Schriftsteller","Paris#Schweiz"},
				{"Orff, Carl","m","1895","1982","Komponist#Bearbeiter#Kapellmeister#Musikpädagoge#Musikforscher#Musikschriftsteller#Kompositionslehrer#Musikdokumentar#Pianist#Organist#Violoncellist#Textdichter#Instrumentenbauer#Cembalist","","Ägypten#Darmstadt#Frankfurt/Main#Japan#Kanada#Mannheim#Portugal#Salzburg#Venedig#München"},
				{"Dittersdorf, Karl Ditters von","m","1739","1799","Komponist#Kapellmeister#Geiger#Musikpädagoge","Verwalter#Adliger","Berlin#Bologna#Breslau#Brünn#Frankfurt/Main#Hildburghausen#Parma#Prag#Triest#Troppau#Venedig#Wien"},
				{"Graun, Karl Heinrich","m","1703","1759","Komponist#Kapellmeister#Tenor#Diskantist#Pianist#Cembalist#Organist#Violoncellist#Musikpädagoge","","Bayreuth#Bologna#Braunschweig#Dresden#Florenz#Leipzig#Magdeburg#Neapel#Prag#Rom#Venedig#Berlin"},
				{"Kodály, Zoltán","m","1882","1967","Komponist#Musikdokumentar#Volksliedsammler","","Bayreuth#Berlin#Budapest#Chicago#Italien#Jerusalem#München#Paris#Salzburg#Zürich"},
				{"Gottsched, Johann Christoph","m","1700","1766","Musikschriftsteller","Schriftsteller#Philosoph#Gelehrter#Professor#Journalist#Intendant#Rektor","Königsberg#Wien#Leipzig"},
				{"Schweitzer, Albert","m","1875","1965","Organist#Musikforscher#Musikschriftsteller#Herausgeber","Arzt#Theologe#Philosoph","Bayreuth#Berlin#München#Paris#Straßburg#Wien"},
				{"Schumann, Clara","w","1819","1896","Pianist#Komponist","","Belgien#Berlin#Bremen#Dresden#Düsseldorf#Frankfurt/Main#Hamburg#Kassel#Königsberg#Kopenhagen#Leipzig#London#Mainz#Niederlande#Paris#Riga#St. Petersburg#Weimar#Wien"},
				{"Reichardt, Johann Friedrich","m","1752","1814","Komponist#Musikschriftsteller#Kapellmeister#Musikredakteur","Jurist#Schriftsteller","Berlin#Dresden#Kassel#Kopenhagen#Leipzig#London#Neapel#Paris#Potsdam#Rom#Stockholm#Wien"},
				{"Friedrich (4)","m","1657","1713","","König#Kurfürst","Berlin"},
				{"Abbado, Claudio","m","1933","2014","Dirigent","","Berlin#Chicago#Japan#London#Mailand#München#New York#Parma#Salzburg#Triest#Wien"},
				{"Weill, Kurt Julian","m","1900","1950","Komponist#Kapellmeister#Dirigent#Bearbeiter","","Berlin#Dessau#London#New York#Paris#Parma#Venedig"},
				{"Rameau, Jean-Philippe","m","1683","1764","Komponist#Musikschriftsteller#Geiger#Organist","","Avignon#Lyon#Mailand#Paris"},
				{"Genzmer, Harald","m","1909","2007","Komponist#Pianist#Organist#Klarinettist#Kompositionslehrer#Musikpädagoge","","Berlin#Breslau#Freiburg/Breisgau#Marburg#München#Rostock"},
				{"Karl Theodor","m","1724","1799","Gambist#Violoncellist#Flötist#Geiger#Mäzen","Kurfürst","München#Mannheim"},
				{"Friedrich Wilhelm","m","1620","1688","Gambist#Musikliebhaber","Kurfürst#Markgraf#Herzog","Berlin#Niederlande#Warschau"},
				{"Massenet, Jules","m","1842","1912","Komponist","","Budapest#Deutschland#Rom#Venedig#Paris"},
				{"Ett, Caspar","m","1788","1847","Komponist#Organist#Musikforscher#Musikpädagoge#Gesangslehrer#Klavierlehrer#Violoncellist#Tenor#Bearbeiter#Chorknabe","Historiker","Andechs#München"},
				{"Praetorius, Michael","m","1573","1621","Organist#Kapellmeister#Komponist#Musikforscher","","Dresden#Frankfurt/Oder#Halle#Kassel#Leipzig#Magdeburg#Nürnberg#Prag#Regensburg#Sondershausen#Wolfenbüttel"},
				{"Clementi, Muzio","m","1752","1832","Pianist#Komponist#Dirigent#Kapellmeister#Organist#Musikverleger#Musikalienhändler#Klavierbauer#Klavierlehrer#Musikschriftsteller#Musikdokumentar","","Berlin#Bern#Dresden#Frankfurt/Main#Leipzig#Lyon#München#Paris#Riga#Rom#St. Petersburg#Straßburg#Wien#Zürich#London"},
				{"Abraham a Sancta Clara, Johann Ulrich","m","1644","1709","Komponist#Textdichter","Pfarrer#Mönch#Schriftsteller","Graz#Ingolstadt#Prag#Rom#Wien"},
				{"Krenek, Ernst","m","1900","1991","Komponist#Pianist#Dirigent#Kompositionslehrer#Musikschriftsteller#Textdichter","Professor#Soldat","Berlin#Darmstadt#Kassel#Nürnberg#Paris#Schweiz#Wien"},
				{"Bruch, Max","m","1838","1920","Komponist#Dirigent#Pianist","","Berlin#Bonn#Breslau#Brüssel#Dresden#Hannover#Koblenz#Köln#Leipzig#Mannheim#München#Paris#Sondershausen#Wien"},
				{"Caldara, Antonio","m","1670","1736","Komponist#Kapellmeister#Violoncellist#Geiger#Cembalist#Musikpädagoge#Chorknabe","","Barcelona#Genua#Mailand#Prag#Rom#Salzburg#Venedig#Wien"},
				{"Byrd, William","m","1543","1623","Komponist#Organist","","London"},
				{"Thoma, Ludwig","m","1867","1921","Volksliedsammler#Textdichter","Jurist#Journalist#Schriftsteller","Aschaffenburg#Dachau#Rottach-Egern#Tegernsee#München"},
				{"Diabelli, Anton","m","1781","1858","Komponist#Pianist#Geiger#Gitarrist#Klavierlehrer#Gitarrenlehrer#Sänger#Musikverleger#Bearbeiter#Chorknabe","Mönch#Geistlicher","München#Salzburg#Wien"},
				{"Nestroy, Johann Nepomuk Eduard Ambrosius","m","1801","1862","Bassist#Bariton#Textdichter","Schriftsteller#Intendant#Schauspieler","Amsterdam#Bratislava#Brünn#Graz#Klagenfurt#Wien"},
				{"Pachelbel, Johann","m","1653","1706","Komponist#Organist#Musikpädagoge","","Altdorf#Erfurt#Nürnberg#Regensburg#Stuttgart#Wien"},
				{"Vanhal, Johann Baptist","m","1739","1813","Komponist#Organist#Musikpädagoge","","Italien#Kroatien#Wien"},
				{"George, Stefan","m","1868","1933","Textdichter","Dichter#Übersetzer","Basel#Belgien#Berlin#Darmstadt#Griechenland#Heidelberg#Italien#Kopenhagen#London#München#Niederlande#Paris#Schweiz#Spanien#Wien"},
				{"Kreutzer, Konradin","m","1780","1849","Komponist#Dirigent#Organist","Jurist","Nürnberg#Riga#Schweiz#Stuttgart#Wien"},
				{"Desprez, Josquin","m","1450","1521","Komponist#Kapellmeister#Dirigent#Sänger#Chorknabe","Pfarrer","Mailand#Rom"},
				{"Jommelli, Niccolò","m","1714","1774","Komponist#Kapellmeister#Dirigent","","Bologna#Ludwigsburg#Mannheim#Neapel#Rom#Stuttgart#Tübingen#Venedig#Wien"},
				{"Hartmann von Aue","m","1160","1210","Minnesänger","Dichter#Übersetzer#Ritter#Gelehrter",""},
				{"Scheffel, Joseph Victor von","m","1826","1886","Musikaliensammler","Maler#Jurist#Schriftsteller#Adliger","Berlin#Bruchsal#Heidelberg#Karlsruhe#München"},
				{"Bloch, Ernst Simon","m","1885","1977","Musikforscher#Musikschriftsteller","Philosoph#Physiker#Professor","Berlin#Garmisch-Partenkirchen#Heidelberg#Leipzig#München#New York#Paris#Prag#Tübingen#Wien#Würzburg#Zürich"},
				{"Friedrich Wilhelm (3)","m","1770","1840","Komponist#Widmungsträger","König#Markgraf#Kurfürst","Jena#Memel#Paris#Berlin"},
				{"Albinoni, Tomaso Giovanni","m","1671","1751","Komponist#Dirigent#Sänger#Geiger#Gesangslehrer","Unternehmer","Florenz#Genua#Mailand#München#Venedig"},
				{"Selnecker, Nikolaus","m","1528","1592","Textdichter#Komponist#Organist","Theologe#Dichter#Professor#Pfarrer","Braunschweig#Dresden#Jena#Leipzig#Oldenburg#Wittenberg"},
				{"Vogler, Georg Joseph","m","1749","1814","Komponist#Kapellmeister#Organist#Pianist#Musikpädagoge#Gesangslehrer#Musikforscher#Orgelbauer","Geistlicher#Lehrer","Amsterdam#Athen#Bamberg#Berlin#Bologna#Breslau#Darmstadt#Frankfurt/Main#Gibraltar#Hamburg#Kopenhagen#London#Mainz#Mannheim#München#Padua#Paris#Portugal#Prag#Rom#Russland#Stockholm#Venedig#Wien#Würzburg"},
				{"Strauss, Johann Baptist","m","1804","1849","Komponist#Kapellmeister#Dirigent#Geiger","Handwerker#Soldat","Wien"},
				{"Vaughan Williams, Ralph","m","1872","1958","Komponist#Chorleiter#Organist#Musikpädagoge#Musikforscher#Volksliedsammler","","Bayreuth#Berlin#London#Paris#USA"},
				{"Kraus, Karl (2)","m","1874","1936","Textdichter#Musikschriftsteller","Schriftsteller#Schauspieler","Berlin#München#Paris#Wien"},
				{"Hensel, Fanny","w","1805","1847","Komponist#Pianist#Sänger#Chorleiter#Dirigent","","Berlin"},
				{"Besold, Christoph","m","1577","1638","Musikdokumentar","Geisteswissenschaftler#Rat#Jurist#Lehrer#Historiker#Professor","Ingolstadt#Tübingen"},
				{"Stamitz, Karl","m","1745","1801","Geiger#Komponist#Kapellmeister#Musikpädagoge#Bratscher","","Amsterdam#Augsburg#Berlin#Braunschweig#Dresden#Frankfurt/Main#Greiz#Halle#Hamburg#Jena#Leipzig#London#Lübeck#Magdeburg#Mannheim#Nürnberg#Paris#Prag#Straßburg#Versailles#Weimar#Wien"},
				{"Mayr, Johann Simon","m","1763","1845","Komponist#Kapellmeister#Organist#Musikpädagoge#Kompositionslehrer#Musikdokumentar#Musikaliensammler#Instrumentalist#Sänger#Chorknabe","","Ingolstadt#Mailand#München#Neapel#Venedig"},
				{"Riemann, Hugo","m","1849","1919","Musikforscher#Musikpädagoge#Klavierlehrer#Musikschriftsteller#Pianist#Dirigent","Professor#Jurist#Historiker#Philologe#Philosoph#Soldat","Berlin#Bielefeld#Edinburgh#Florenz#Göttingen#Leipzig#Rom#Tübingen"},
				{"Marx, Karl","m","1897","1985","Komponist#Pianist#Chorleiter#Dirigent#Musikpädagoge#Korrepetitor#Kompositionslehrer","Naturwissenschaftler#Professor","Graz#Ingolstadt#Stuttgart#München"},
				{"Distler, August Hugo","m","1908","1942","Komponist#Organist#Chorleiter#Musikpädagoge#Kompositionslehrer#Orgellehrer#Orgelsachverständiger#Musikforscher","","Berlin#Donaueschingen#Graz#Leipzig#Lübeck#Stuttgart"},
				{"Wedekind, Frank","m","1864","1918","Unterhaltungskünstler#Sänger#Gitarrist","Jurist#Schriftsteller","Berlin#London#Paris#Zürich#München"},
				{"Suppé, Franz von","m","1819","1895","Komponist#Kapellmeister#Flötist#Dirigent#Pianist","Ritter#Jurist","Bayreuth#Bratislava#Mailand#Padua#Paris#Sopron#Wien"},
				{"Iffland, August Wilhelm","m","1700","1778","Sänger","Schauspieler",""},
				{"Canisius, Petrus","m","1521","1597","Sänger","Theologe#Schriftsteller#Professor#Geistlicher#Mönch","Augsburg#Bologna#Dillingen/Donau#Freiburg/Üechtland#Ingolstadt#Innsbruck#Köln#Mainz#München#Prag#Regensburg#Rom#Wien"},
				{"Rinck, Johann Christian Heinrich","m","1770","1846","Komponist#Organist#Chorleiter#Musikpädagoge#Musikschriftsteller#Orgelsachverständiger","","Darmstadt#Erfurt#Gießen"},
				{"Geibel, Emanuel","m","1815","1884","Textdichter","Dichter#Professor#Übersetzer","Athen#Berlin#Bonn#Griechenland#Lübeck#München"},
				{"Gretry, André-Ernest-Modeste","m","1741","1813","Komponist","","Bologna#Genf#Paris#Rom"},
				{"Gabrieli, Giovanni","m","1557","1613","Komponist#Organist","","München#Venedig"},
				{"Victoria, Tomás Luis de","m","1548","1611","Komponist#Organist#Sänger","","Madrid#Rom"},
				{"Tartini, Giuseppe","m","1692","1770","Komponist#Geiger","Jurist","Padua#Prag"},
				{"Kepler, Johannes","m","1571","1630","Musikdokumentar#Musikschriftsteller","Mathematiker#Physiker#Lehrer#Diener","Graz#Linz#Prag#Tübingen"},
				{"Gautier, Théophile","m","1811","1872","Textdichter#Musikliebhaber#Komponist","Schriftsteller#Journalist","Belgien#England#Griechenland#Italien#Niederlande#Paris#Russland#Spanien#Wiesbaden"},
				{"Raff, Joseph Joachim","m","1822","1882","Komponist#Musikschriftsteller#Musikpädagoge","Lehrer","Basel#Frankfurt/Main#Hamburg#Köln#Stuttgart#Weimar#Wiesbaden"},
				{"Dilherr, Johann Michael","m","1604","1669","Komponist#Textdichter#Musikschriftsteller","Geistlicher#Lehrer#Schriftsteller#Theologe#Bibliothekar#Schulleiter","Altdorf#Jena#Leipzig#Nürnberg"},
				{"Quantz, Johann Joachim","m","1697","1773","Flötist#Komponist#Musikalischer Leiter#Geiger#Oboist#Hornist#Trompeter#Posaunist#Fagottist#Gambist#Violoncellist#Kontrabassist#Pianist#Musikpädagoge#Kompositionslehrer#Flötenlehrer#Instrumentenkundler#Flötenbauer#Musikdokumentar","","Bayreuth#Berlin#Bologna#Dresden#Florenz#Genf#London#Lyon#Mailand#Neapel#Niederlande#Padua#Paris#Parma#Potsdam#Prag#Rom#Turin#Venedig#Warschau#Wien"},
				{"Bach, Wilhelm Friedemann","m","1710","1784","Organist#Orgellehrer#Cembalist#Klavierlehrer#Komponist","Jurist#Philosoph#Mathematiker","Braunschweig#Dresden#Leipzig"},
				{"Mozart, Johann Georg Leopold","m","1719","1787","Komponist#Kapellmeister#Musikpädagoge#Geiger#Organist#Geigenlehrer#Klavierlehrer#Musikdokumentar#Sänger#Musikschriftsteller","Diener#Schauspieler","Augsburg#England#Frankreich#Italien#München#Niederlande#Schweiz#Wien#Salzburg"},
				{"Humperdinck, Engelbert","m","1854","1921","Komponist#Dirigent#Kapellmeister#Kompositionslehrer#Musikschriftsteller#Musikredakteur#Pianist#Organist#Kopist","Professor","Ägypten#Barcelona#Bayreuth#Berlin#Bonn#Boppard#Essen#Frankfurt/Main#Karlsruhe#Koblenz#Köln#London#Mainz#Meran#München#Neapel#New York#Paderborn#Paris#Rom#Weimar#Wien"},
				{"Cochlaeus, Johann","m","1479","1552","Musikdokumentar#Musikpädagoge#Chorleiter#Cembalist","Geisteswissenschaftler#Lehrer#Geistlicher#Historiker#Theologe","Augsburg#Bologna#Breslau#Dresden#Eichstätt#Frankfurt/Main#Ingolstadt#Köln#Leipzig#Mainz#Nürnberg#Pfarrkirchen#Regensburg#Rom"},
				{"Cornelius, Peter","m","1824","1874","Komponist#Geiger#Musikpädagoge#Musikredakteur#Textdichter","Übersetzer#Beamter#Schriftsteller#Schauspieler","Basel#Bayreuth#Berlin#England#Luzern#Mainz#München#Paris#Tirol#Weimar#Wien#Wiesbaden#Zürich"},
				{"Rosetti, Francesco Antonio","m","1750","1792","Komponist#Kapellmeister#Kontrabassist#Geiger","Diener#Lehrer","Ansbach#Augsburg#Berlin#Darmstadt#Frankfurt/Main#Ludwigslust#Mainz#München#Paris#Prag#Russland#Speyer#Wallerstein#Weimar#Znaim"},
				{"Lotti, Antonio","m","1666","1740","Altist#Organist#Komponist#Kapellmeister#Musikschriftsteller","","Dresden#Venedig"},
				{"Arnim, Bettina von","w","1785","1859","Textdichter","Schriftsteller","Berlin#Frankfurt/Main#Kassel#Marburg"},
				{"Haßler, Hans Leo von","m","1564","1612","Komponist#Organist#Orgelsachverständiger#Musikalischer Leiter#Musikpädagoge#Instrumentenbauer","Bankkaufmann#Handwerker#Händler#Diener","Augsburg#Dresden#Frankfurt/Main#Nürnberg#Prag#Ulm#Venedig"},
				{"Salieri, Antonio","m","1750","1825","Komponist#Kapellmeister#Musikpädagoge","Intendant","Frankfurt/Main#Mailand#Padua#Paris#Rom#Triest#Venedig#Wien"},
				{"Walther","m","1170","1230","Minnesänger#Komponist#Sänger","Schriftsteller","Frankreich#Italien#Kärnten#Passau#Schwaben#Thüringen#Wien#Würzburg"},
				{"Furtwängler, Wilhelm","m","1886","1954","Dirigent#Kapellmeister#Chorleiter#Pianist#Komponist#Musikschriftsteller","Intendant","Ägypten#Bayreuth#Berlin#Breslau#Florenz#Frankfurt/Main#Leipzig#London#Lübeck#Mannheim#München#New York#Paris#Salzburg#Straßburg#USA#Wien#Zürich"},
				{"Silcher, Friedrich","m","1789","1860","Komponist#Volksliedsammler#Pianist#Chorleiter#Dirigent#Musikpädagoge#Musikalischer Leiter","Lehrer","Ludwigsburg#Tübingen"},
				{"Weigel, Christoph","m","1654","1725","Notendrucker#Musikverleger#Musikschriftsteller","Verleger#Händler#Schriftsteller","Augsburg#Frankfurt/Main#Hof#Jena#Regensburg#Wien#Nürnberg"},
				{"Wilhelm (5)","m","1859","1941","","","Berlin#Wiesbaden"},
				{"Biebl, Franz","m","1906","2001","Komponist#Chorleiter#Dirigent#Organist#Pianist#Musikpädagoge","Lehrer#Soldat","Amberg#Fürstenfeldbruck#München#Salzburg"},
				{"Callas, Maria","w","1923","1977","Sopranist#Gesangslehrer","Schauspieler","Athen#Berlin#Edinburgh#Florenz#London#Mailand#New York#Palermo#Paris#Rom#San Francisco#Turin#Venedig#Verona#Wien"},
				{"Hoffmeister, Franz Anton","m","1754","1812","Musikverleger#Komponist","Jurist","Leipzig#Linz#Wien"},
				{"Moser, Hans Joachim","m","1889","1967","Musikforscher#Musikpädagoge#Komponist#Sänger#Pianist","Professor#Geisteswissenschaftler","Halle#Heidelberg#Jena#Königsberg#Leipzig#Marburg#Rostock#Weimar#Berlin"},
				{"Steffani, Agostino","m","1654","1728","Komponist#Kapellmeister#Cembalist#Organist#Sänger#Diskantist#Chorknabe","Politiker#Professor#Geistlicher#Theologe#Diplomat#Rat#Abt#Bischof","Braunschweig#Brüssel#Dresden#Düsseldorf#Frankfurt/Main#Hannover#Heidelberg#Köln#Lüneburg#Mainz#Münster#Neuburg/Donau#Padua#Paris#Rom#Turin#Venedig#Wien#München"},
				{"Kagel, Mauricio","m","1931","2008","Komponist#Dirigent#Pianist#Violoncellist#Musikforscher#Chorleiter#Kompositionslehrer","Professor#Philosoph","Berlin#Buenos Aires#Darmstadt#München#USA#Köln"},
				{"Winter, Peter von","m","1754","1825","Komponist#Kapellmeister#Geiger#Kontrabassist#Gesangslehrer","Adliger","London#Mailand#Mannheim#Neapel#Paris#Prag#Venedig#Wien#München"},
				{"Abt, Franz","m","1819","1885","Komponist#Konzertmeister#Chorleiter#Kapellmeister#Dirigent","","Leipzig#Moskau#Paris#Riga#St. Petersburg#USA#Wiesbaden#Zürich#Braunschweig"},
				{"Fasch, Johann Friedrich","m","1688","1758","Komponist#Chorknabe","Dichter","Bamberg#Bayreuth#Berlin#Darmstadt#Dresden#Frankfurt/Main#Gießen#Greiz#Kassel#Leipzig#Marburg#Nürnberg#Suhl#Weißenfels"},
				{"Trithemius, Johannes","m","1462","1516","Musikdokumentar","Gelehrter#Kulturwissenschaftler#Geistlicher","Heidelberg#Würzburg"},
				{"Joachim, Joseph","m","1831","1907","Geiger#Komponist#Dirigent#Konzertmeister#Musikpädagoge#Geigenlehrer","","Belgien#Berlin#Bonn#Budapest#Dresden#Düsseldorf#Göttingen#Hannover#Köln#Leipzig#London#Niederlande#Prag#Rom#Weimar#Wien"},
				{"Danzi, Franz Ignaz","m","1763","1826","Komponist#Dirigent#Kapellmeister#Violoncellist#Musikpädagoge#Kompositionslehrer#Musikschriftsteller","","Florenz#Frankfurt/Main#Hamburg#Karlsruhe#Leipzig#Mannheim#München#Prag#Stuttgart#Venedig"},
				{"Brod, Max (2)","m","1884","1968","Komponist#Pianist#Textdichter#Musikschriftsteller","Schriftsteller#Übersetzer#Philosoph","Prag"},
				{"Lachner, Franz Paul","m","1803","1890","Dirigent#Kapellmeister#Komponist#Organist#Musikpädagoge#Geiger#Violoncellist#Hornist#Kontrabassist","","Mannheim#Wien#München"},
				{"Schering, Arnold","m","1877","1941","Musikforscher#Musikschriftsteller#Geiger","Professor","Berlin#Dresden#Leipzig#München"},
				{"Bialas, Günter","m","1907","1995","Komponist#Musikpädagoge#Kompositionslehrer#Musikforscher#Pianist#Musikalischer Leiter","Professor#Soldat","Berlin#Breslau#Detmold#München#Weimar"},
				{"Palladio, Andrea","m","1508","1580","Musiker","Architekt","Rom#Venedig#Vicenza"},
				{"Paer, Ferdinand","m","1771","1839","Komponist#Kapellmeister#Dirigent","","Dresden#Paris#Parma#Venedig#Wien"},
				{"Maximilian I.","m","1459","1519","Mäzen#Musikliebhaber","Kaiser","Deutschland#Österreich"},
				{"Böhm, Karl","m","1894","1981","Dirigent#Pianist","Jurist","Bayreuth#Berlin#Darmstadt#Dresden#Graz#Hamburg#Japan#München#Wien"},
				{"Biber, Heinrich Ignaz Franz","m","1644","1704","Komponist#Kapellmeister#Chorleiter#Dirigent#Geiger#Instrumentalist#Musikpädagoge#Gesangslehrer","Diener#Lehrer","Graz#Kremsier#Linz#München#Wien#Salzburg"},
				{"Naumann, Johann Gottlieb","m","1741","1801","Komponist#Kapellmeister#Dirigent","","Berlin#Bologna#Hamburg#Kopenhagen#München#Padua#Schwerin#Stockholm#Venedig#Dresden"},
				{"Dessau, Paul","m","1894","1979","Komponist#Kapellmeister#Dirigent#Korrepetitor#Musikpädagoge#Geiger#Sänger","Soldat","Berlin#Bremen#Hamburg#New York#Paris"},
				{"Durante, Francesco","m","1684","1755","Komponist#Kapellmeister#Cembalist#Geiger#Musikpädagoge#Sänger","","Neapel#Rom"},
				{"Kalliwoda, Johann Wenzel","m","1801","1866","Geiger#Komponist#Kapellmeister#Dirigent#Geigenlehrer","","Karlsruhe#Linz#München#Niederlande#Prag#Schweiz#Donaueschingen"},
				{"Ries, Ferdinand","m","1784","1838","Komponist#Pianist#Dirigent#Geiger#Kopist","","Frankfurt/Main#Italien#Koblenz#London#München#Paris#Russland#Schweden#Wien"},
				{"Baumann, Hans","m","1914","1988","Komponist#Sänger#Textdichter#Musikpädagoge","Lehrer#Schriftsteller","Berlin#Frankreich#Furth/Wald#Hamburg#Oberammergau#Passau#Potsdam#Russland#Weimar#Murnau"},
				{"Karg-Elert, Sigfrid","m","1877","1933","Komponist#Pianist#Organist#Klavierlehrer#Musikschriftsteller#Chorknabe","Professor","Leipzig#Magdeburg#München#New York#Stuttgart"},
				{"Brixi, František Xaver","m","1732","1771","Komponist#Dirigent#Organist#Kapellmeister","","Prag"},
				{"David, Johann Nepomuk","m","1895","1977","Komponist#Chorleiter#Organist#Musikpädagoge#Kompositionslehrer#Orgelsachverständiger#Sänger#Chorknabe","Lehrer","Basel#Berlin#Bremen#Darmstadt#Freiburg/Breisgau#Hamburg#Leipzig#Linz#Metz#Nancy#Paris#Prag#Salzburg#Stuttgart#Wien"},
				{"Fux, Johann Joseph","m","1660","1741","Komponist#Kapellmeister#Dirigent","","Graz#Ingolstadt#Wien"},
				{"Friedrich Wilhelm (5)","m","1744","1797","","","Berlin"},
				{"Anzengruber, Ludwig","m","1839","1889","Unterhaltungskünstler","","Wien"},
				{"Theopold, Hans-Martin","m","1904","2000","Pianist#Musikpädagoge#Klavierlehrer","","Berlin#Bielefeld#Bremen#Stuttgart#Würzburg"},
				{"Zelenka, Jan Dismas","m","1674","1745","Komponist#Kapellmeister#Dirigent#Kontrabassist","","Dresden#Prag#Wien"},
				{"Albrechtsberger, Johann Georg","m","1736","1809","Musikforscher#Komponist#Organist#Violoncellist#Kapellmeister#Dirigent#Kompositionslehrer#Chorknabe#Orgelbauer","Lehrer#Philosoph","Klosterneuburg#Wien"},
				{"Gerson, Johannes","m","1363","1429","Musikforscher#Musikschriftsteller","Theologe#Schriftsteller#Professor","Avignon#Konstanz#Lyon#Paris"},
				{"Moscheles, Ignaz","m","1794","1870","Pianist#Komponist#Dirigent","","Dresden#Leipzig#London#München#Paris#Prag#Wien"},
				{"Solti, Georg","m","1912","1997","Dirigent#Kapellmeister#Pianist","","Bayreuth#Budapest#Buenos Aires#Chicago#Frankfurt/Main#Genf#London#München#Paris#Salzburg#USA"},
				{"Maximilian","m","1727","1777","Komponist#Gambist#Geiger#Bratscher#Violoncellist#Pianist#Flötist#Mäzen","Kurfürst","München"},
				{"Schwarzkopf, Elisabeth","w","1915","2006","Sopranist#Gesangslehrer","","Bayreuth#Berlin#Brüssel#Chicago#London#Luzern#Mailand#New York#Salzburg#San Francisco#Venedig#Wien#Zürich"},
				{"Méhul, Etienne Nicolas","m","1763","1817","Komponist","Professor","Paris"},
				{"Fortner, Wolfgang","m","1907","1987","Komponist#Kompositionslehrer#Dirigent#Musikforscher#Veranstalter","","Berlin#Detmold#Heidelberg#Leipzig#München#Salzburg"},
				{"Maximilian (2)","m","1573","1651","Mäzen#Organist","Kurfürst","München"},
				{"Görres, Joseph von","m","1776","1848","Musikschriftsteller","Professor","München"},
				{"Zemlinsky, Alexander von","m","1871","1942","Komponist#Dirigent#Kapellmeister","","Berlin#Prag#USA#Wien"},
				{"Jöde, Fritz","m","1887","1970","Musikpädagoge#Volksliedsammler#Musikforscher#Chorleiter#Gesangslehrer#Bearbeiter#Herausgeber#Veranstalter","Lehrer#Professor","Bad Reichenhall#Berlin#Braunschweig#Frankfurt/Main#Leipzig#München#Salzburg#Stuttgart#Trossingen#Hamburg"},
				{"Gesner, Johann Matthias","m","1691","1761","Widmungsträger#Musikliebhaber","Bibliothekar#Professor#Schulleiter","Göttingen#Leipzig#Weimar"},
				{"Jonas, Justus","m","1493","1555","Komponist#Textdichter","Geistlicher#Schriftsteller#Theologe#Übersetzer#Jurist","Coburg#Eisleben#Erfurt#Halle#Jena#Regensburg#Wittenberg"},
				{"Harsdörffer, Georg Philipp","m","1607","1658","Textdichter","Dichter#Übersetzer#Jurist#Rat#Geisteswissenschaftler","Altdorf#Frankreich#Italien#Niederlande#Schweiz#Siena#Straßburg#Nürnberg"},
				{"Benda, Georg Anton","m","1722","1795","Komponist#Kapellmeister#Dirigent#Cembalist#Pianist#Geiger#Oboist","","Berlin#Bologna#Florenz#Hamburg#Heidelberg#Mannheim#Paris#Potsdam#Rom#Venedig#Wien"},
				{"Friedrich Wilhelm (4)","m","1795","1861","Musikliebhaber","König#Schriftsteller","Berlin#Paris#Rom"},
				{"Bresgen, Cesar","m","1913","1988","Komponist#Organist#Kompositionslehrer#Dirigent#Chorleiter#Textdichter#Musikforscher#Bearbeiter#Volksliedsammler","Naturwissenschaftler#Schriftsteller#Maler#Professor","London#Mittersill#München#Salzburg"},
				{"Kirchner, Theodor","m","1823","1903","Organist#Pianist#Dirigent#Musikpädagoge","","Chemnitz#Dresden#Düsseldorf#Hamburg#Leipzig#Meiningen#Winterthur#Würzburg#Zürich"},
				{"Martini, Johann Baptist","m","1706","1784","Komponist#Kapellmeister#Musikforscher#Musikpädagoge#Organist#Geiger#Violoncellist","","Florenz#Rom#Siena#Bologna"},
				{"Riehl, Wilhelm Heinrich","m","1823","1897","Musikforscher#Musikschriftsteller","Professor#Schriftsteller#Kunstwissenschaftler#Historiker#Theologe#Philosoph","Augsburg#Bonn#Frankfurt/Main#Gießen#Karlsruhe#Marburg#Tübingen#Wiesbaden#München"},
				{"Albert, Eugen d&apos;&apos;","m","1864","1932","Komponist#Pianist#Dirigent","","Berlin#London#Riga#Weimar#Wien"},
				{"Stolz, Robert Elisabeth","m","1880","1975","Dirigent#Komponist","Schauspieler#Professor","Berlin#Brünn#Graz#Israel#Marburg/Drau#München#New York#Russland#Salzburg#Wien"},
				{"Schikaneder, Joseph Johann Emanuel","m","1751","1812","Bariton#Komponist#Textdichter#Tänzer#Musiktheaterregisseur","Schauspieler#Intendant#Schriftsteller","Augsburg#Bratislava#Brünn#Budapest#Erlangen#Graz#Innsbruck#Klagenfurt#Linz#Ljubljana#Memmingen#München#Neuburg/Donau#Nürnberg#Regensburg#Rothenburg/Tauber#Salzburg#Stuttgart#Ulm#Wien"},
				{"Stuntz, Joseph Hartmann","m","1793","1859","Komponist#Kapellmeister#Geiger","","Mailand#Turin#Venedig#Wien#München"},
				{"Graun, Johann Gottlieb","m","1703","1771","Komponist#Geiger#Konzertmeister#Kapellmeister#Sänger#Geigenlehrer","","Berlin#Dresden#Leipzig#Prag"},
				{"Hartmann, Karl Amadeus","m","1905","1963","Komponist#Pianist","","Berlin#Genf#Wien#München"},
				{"Bühler, Franz","m","1760","1823","Komponist#Kapellmeister#Organist#Orgellehrer#Sänger#Chorknabe","Geistlicher#Lehrer","Donauwörth#Konstanz#Maihingen#Augsburg"},
				{"Schubart, Christian Friedrich Daniel","m","1739","1791","Komponist#Musikschriftsteller#Musikpädagoge#Organist","Schriftsteller#Theologe","Augsburg#Erlangen#Ludwigsburg#Memmingen#Nürnberg#Ulm"},
				{"Ringelnatz, Joachim","m","1883","1934","Unterhaltungskünstler","Schriftsteller","Berlin#München"},
				{"Piccinni, Niccolò","m","1728","1800","Komponist#Kapellmeister#Dirigent#Pianist","","Bologna#Florenz#Neapel#Paris#Turin#Venedig"},
				{"Andersch, Alfred","m","1914","1980","Geiger","Buchhändler#Schriftsteller","München"},
				{"Mattheson, Johann","m","1681","1764","Kapellmeister#Pianist#Komponist#Dirigent#Geiger#Flötist#Oboist#Lautenist#Gambist#Organist#Cembalist#Sopranist#Musikpädagoge#Musikschriftsteller#Musikverleger","Diplomat#Sekretär#Jurist","Amsterdam#Braunschweig#Hannover#Leipzig#Hamburg"},
				{"Keiser, Reinhard","m","1674","1739","Komponist#Kapellmeister#Chorleiter#Dirigent#Musikpädagoge","","Hamburg#Kopenhagen#Leipzig#Stuttgart"},
				{"Reißiger, Carl Gottlieb","m","1798","1859","Komponist#Kapellmeister#Chorleiter#Pianist#Musikpädagoge#Kompositionslehrer#Diskantist#Altist#Organist#Geiger","Theologe","Berlin#Bologna#Florenz#Genua#Karlsbad#Leipzig#Mailand#München#Neapel#Niederlande#Paris#Rom#Turin#Wien#Dresden"},
				{"Weingartner, Felix","m","1863","1942","Dirigent#Komponist#Pianist#Musikschriftsteller#Kapellmeister","","Basel#Berlin#Darmstadt#Graz#Hamburg#Königsberg#Leipzig#Mannheim#München#Weimar#Wien"},
				{"Scharfenberger, Werner","m","1925","2001","Komponist#Pianist#Organist#Bearbeiter#Geiger#Unterhaltungskünstler#Chorknabe","","München#Regensburg"},
				{"Rosendorfer, Herbert Friedrich Johann","m","1934","2012","Musikschriftsteller#Komponist","Jurist#Schriftsteller#Professor#Maler#Philologe","Bayreuth#München"},
				{"Reuchlin, Johannes","m","1455","1522","Komponist#Chorknabe","Gelehrter#Professor","Heidelberg#Ingolstadt#Italien#Paris#Pforzheim#Stuttgart"},
				{"Sawallisch, Wolfgang","m","1923","2013","Dirigent#Pianist#Korrepetitor","Intendant#Professor#Soldat","Aachen#Augsburg#Bayreuth#Berlin#Florenz#Genf#Genua#Hamburg#Israel#Köln#London#Mailand#München#Paris#Philadelphia#Rom#Salzburg#Schweiz#Venedig#Wien#Wiesbaden#Grassau"},
				{"Carissimi, Giacomo","m","1605","1674","Komponist#Kapellmeister#Organist#Sänger#Musikpädagoge","Geistlicher","Rom"},
				{"Eberlin, Johann Ernst","m","1702","1762","Komponist#Organist#Kapellmeister#Musikpädagoge#Instrumentallehrer","Adliger","Augsburg#Salzburg"},
				{"Sacchini, Antonio Maria Gasparo Gioacchino","m","1730","1786","Komponist#Kapellmeister#Gesangslehrer#Musikpädagoge#Geiger","","Florenz#London#Mailand#Monaco#München#Neapel#Padua#Paris#Pavia#Rom#Stuttgart#Turin#Venedig#Versailles"},
				{"Lincke, Paul","m","1866","1946","Komponist#Kapellmeister#Fagottist#Geiger#Pianist","","Arzberg#Paris#USA#Wittenberg#Berlin"},
				{"Vischer, Friedrich Theodor von","m","1807","1887","Musikforscher","Professor#Theologe#Philosoph#Philologe","Frankfurt/Main#Zürich#Tübingen"},
				{"Porpora, Nicola","m","1686","1768","Komponist#Kapellmeister#Chorleiter#Musikpädagoge#Gesangslehrer","","Dresden#London#Neapel#Rom#Venedig#Wien"},
				{"Franck, Melchior","m","1579","1639","Komponist#Kapellmeister#Dirigent","","Augsburg#Coburg#Nürnberg"},
				{"Kolneder, Walter","m","1910","1994","Musikforscher#Komponist#Dirigent#Bratscher#Gambist","Professor#Schulleiter","Darmstadt#Graz#Innsbruck#Karlsruhe#Luxemburg#Saarbrücken#Salzburg#Wien"},
				{"Kircher, Athanasius","m","1601","1680","Musikschriftsteller","Pfarrer#Mönch#Diener#Mathematiker#Physiker#Philosoph#Theologe#Professor","Aschaffenburg#Avignon#Fulda#Koblenz#Köln#Lyon#Mainz#Malta#Paderborn#Rom#Speyer#Wien#Würzburg"},
				{"Rathgeber, Valentin","m","1682","1750","Komponist#Organist#Chorleiter","Theologe","Augsburg#Bonn#Habach#Köln#Mainz#München#Trier#Wasserburg/Bodensee#Würzburg"},
				{"Krebs, Johann Ludwig","m","1713","1780","Organist#Komponist#Dirigent#Geiger#Pianist#Lautenist#Sänger#Musikpädagoge","","Dresden#Leipzig#Zwickau"},
				{"Jensen, Adolf","m","1837","1879","Komponist","","Bad Reichenhall#Berchtesgaden#Berlin#Dresden"},
				{"Stölzel, Gottfried Heinrich","m","1690","1749","Komponist#Kapellmeister#Musikschriftsteller#Pianist#Sänger#Gesangslehrer#Klavierlehrer","","Augsburg#Bayreuth#Bologna#Breslau#Florenz#Halle#Innsbruck#Leipzig#Linz#Nürnberg#Prag#Rom#Triest#Venedig"},
				{"Hummel, Bertold","m","1925","2002","Komponist#Pianist#Organist#Violoncellist#Chorleiter#Musikpädagoge#Kompositionslehrer","Professor","Ägypten#Australien#Düsseldorf#Freiburg/Breisgau#Japan#Kanada#Paris#Stuttgart#USA#Würzburg"},
				{"Schwarz, Christian Gottlieb","m","1675","1751","Musiker","Schriftsteller#Historiker#Verleger#Professor#Lehrer#Rektor#Bibliothekar","Altdorf#Leipzig#Wittenberg"},
				{"Leonhardt, Gustav","m","1928","2012","Cembalist#Organist#Dirigent#Bearbeiter","Schauspieler#Professor","Amsterdam#Basel#Siena#Wien"},
				{"Davis, Colin","m","1927","2013","Dirigent#Chorleiter#Klarinettist#Pianist","","Amsterdam#Bayreuth#Berlin#Dresden#Edinburgh#Glyndebourne#München#New York#Wien#London"},
				{"Glarean, Heinrich","m","1488","1563","Musikschriftsteller","Schriftsteller#Professor#Gelehrter#Historiker#Mathematiker#Philologe#Naturwissenschaftler","Basel#Bern#Freiburg/Breisgau#Köln#Paris#Wien"},
				{"Pepping, Ernst","m","1901","1981","Komponist#Musikpädagoge#Kompositionslehrer#Musikschriftsteller#Musikforscher","Professor","Baden-Baden#Bremen#Donaueschingen#Duisburg#Essen#Krefeld#Mülheim/Ruhr#Berlin"},
				{"Isaac, Heinrich","m","1450","1517","Komponist#Kapellmeister#Chorleiter#Organist#Musikpädagoge#Sänger","","Augsburg#Florenz#Innsbruck#Konstanz#Nürnberg#Rom#Wien"},
				{"Zentner, Wilhelm","m","1893","1982","Musikredakteur#Musikpädagoge#Musikforscher","Schriftsteller#Intendant#Professor#Soldat","Freiburg/Breisgau#Heidelberg#Karlsruhe#München"},
				{"Himmel, Friedrich Heinrich","m","1765","1814","Pianist#Komponist#Kapellmeister#Klavierlehrer","","Bad Alexandersbad#Dresden#Halle#Hamburg#Karlsbad#Kassel#Königsberg#Kopenhagen#Leipzig#London#Moskau#München#Neapel#Paris#Potsdam#Prag#Riga#Rom#St. Petersburg#Stockholm#Venedig#Villach#Wien#Berlin"},
				{"Prey, Hermann","m","1929","1998","Bariton#Gesangslehrer#Veranstalter","","Aix-en-Provence#Amsterdam#Berlin#Bregenz#Brüssel#Buenos Aires#Chicago#Duisburg#Düsseldorf#Edinburgh#Florenz#Frankfurt/Main#Hamburg#Köln#Kopenhagen#London#Mailand#München#New York#Salzburg#San Francisco#Stuttgart#Wien#Wiesbaden"},
				{"Carulli, Ferdinando","m","1770","1841","Gitarrist#Komponist#Violoncellist#Pianist","","Italien#Wien#Paris"},
				{"Wolf-Ferrari, Ermanno","m","1876","1948","Komponist","","Bayreuth#Mailand#München#Rom#Salzburg#USA#Venedig#Zürich"},
				{"Menuhin, Yehudi","m","1916","1999","Geiger#Dirigent#Bearbeiter#Herausgeber#Musikpädagoge","Adliger","Berlin#Florenz#London#Paris#San Francisco"},
				{"Roth, Eugen","m","1895","1976","Unterhaltungskünstler","Schriftsteller#Journalist","Ettal#Köln#München"},
				{"Gyrowetz, Adalbert","m","1763","1850","Komponist#Dirigent#Geiger#Sänger#Organist#Kapellmeister","Jurist#Philosoph#Sekretär","Berlin#Bologna#Bratislava#Brünn#Brüssel#Dresden#Eisenstadt#Florenz#Genua#London#Lyon#Mailand#München#Neapel#Padua#Paris#Prag#Rom#Schwetzingen#Siena#Venedig#Vicenza#Wien"},
				{"Kirnberger, Johann Philipp","m","1721","1783","Pianist#Geiger#Organist#Cembalist#Kapellmeister#Dirigent#Musikpädagoge#Komponist#Musikschriftsteller","","Berlin#Coburg#Dresden#Leipzig#Lemberg#Potsdam#Sondershausen"},
				{"Haas, Joseph","m","1879","1960","Komponist#Musikpädagoge#Kompositionslehrer#Musikalischer Leiter","","Leipzig#Stuttgart#München"},
				{"Raimund, Ferdinand Jakob","m","1790","1836","Sänger#Komponist#Textdichter","Dichter#Schauspieler#Bäcker#Händler","Berlin#Hamburg#München#Wien"},
				{"Anfossi, Pasquale","m","1727","1797","Komponist","",""},
				{"Wilhelm (7)","m","1797","1888","","","Berlin#Paris"},
				{"Witt, Franz Xaver","m","1834","1888","Kapellmeister#Dirigent#Komponist#Musikschriftsteller#Herausgeber#Chorleiter#Organist","Pfarrer","Bamberg#Eichstätt#Landshut#Rom#Regensburg"},
				{"Bülow, Hans Guido von","m","1830","1894","Dirigent#Pianist#Klavierlehrer#Komponist#Kapellmeister#Musikschriftsteller","Jurist","Berlin#Dresden#Florenz#Hamburg#Leipzig#London#Meiningen#München#Paris#Russland#St. Gallen#Stuttgart#USA#Weimar#Wien#Zürich"},
				{"Walter, Bruno","m","1876","1962","Dirigent#Komponist#Gesangslehrer#Pianist","Schriftsteller","Barcelona#Bayreuth#Berlin#Bratislava#Breslau#Florenz#Hamburg#Köln#Leipzig#London#Moskau#München#New York#Paris#Prag#Riga#Rom#Salzburg#Wien"},
				{"Romberg, Andreas","m","1767","1821","Geiger","","Bonn#Frankfurt/Main#Münster#Paris"},
				{"Blume, Friedrich","m","1893","1975","Musikforscher#Musikpädagoge","Arzt#Philosoph#Historiker#Kunstwissenschaftler#Soldat#Lehrer#Professor","Berlin#Leipzig#Lüneburg#München#Rothenburg/Tauber#Kiel"},
				{"Auger, Arleen","w","1939","1993","Sopranist#Gesangslehrer","","Aix-en-Provence#Amsterdam#Chicago#Duisburg#Düsseldorf#Frankfurt/Main#Hamburg#Köln#London#Mailand#Moskau#München#New York#Paris#Rom#Salzburg#Wien"},
				{"Nono, Luigi","m","1924","1990","Komponist#Kompositionslehrer","","Berlin#Darmstadt#Freiburg/Breisgau#Genf#Hamburg#Köln#Mailand#München#Paris#Prag#Venedig#Warschau#Zürich"},
				{"Wieniawski, Henri","m","1835","1880","Komponist#Geiger","Professor","Brüssel#München#Paris#Warschau"},
				{"Stamitz, Johann Wenzel Anton","m","1717","1757","Komponist#Kapellmeister#Dirigent#Konzertmeister#Geiger#Geigenlehrer","","Frankfurt/Main#Paris#Prag#Mannheim"},
				{"Pocci, Franz von","m","1807","1876","Komponist#Pianist#Textdichter#Musikdokumentar#Musikredakteur","Graf#Maler#Schriftsteller#Jurist#Intendant","Dachau#Landshut#Münsing#Starnberg#München"},
				{"Wagenseil, Georg Christoph","m","1715","1777","Komponist#Pianist#Organist#Musikschriftsteller","","Mailand#Venedig#Wien"},
				{"Welcker, Max","m","1878","1954","Organist#Komponist#Musikpädagoge#Musikschriftsteller","Lehrer","Krumbach#Lauingen#Augsburg"},
				{"Meusel, Johann Georg","m","1743","1820","Musikdokumentar","Professor#Historiker#Rat#Kunstwissenschaftler#Schriftsteller","Bamberg#Erfurt#Erlangen#Halle"},
				{"Bahr, Hermann","m","1863","1934","Musikredakteur","Schriftsteller#Journalist#Regisseur","Berlin#München#Paris#Salzburg#Wien"},
				{"Kraus, Joseph Martin","m","1756","1792","Dirigent#Komponist#Geiger#Pianist#Musikpädagoge","Jurist#Schriftsteller","Erfurt#Florenz#Göttingen#London#Mainz#Mannheim#Neapel#Paris#Rom#Stockholm#Wien"},
				{"Spontini, Gaspare","m","1774","1851","Komponist","","Berlin#Dresden#Florenz#Halle#Köln#Leipzig#London#München#Neapel#Palermo#Rom#Salzburg#Venedig#Weimar#Paris"},
				{"Locatelli, Pietro Antonio","m","1695","1764","Komponist#Geiger#Musikpädagoge#Musikverleger#Musikalienhändler","","Berlin#Dresden#Kassel#München#Rom#Venedig#Amsterdam"},
				{"Senfl, Ludwig","m","1490","1543","Komponist#Kapellmeister#Sänger#Kopist#Diskantist#Chorknabe","Geistlicher#Schreiber","Augsburg#Florenz#Konstanz#Linz#Passau#Verona#Wien#Zürich#München"},
				{"Heller, Stephen","m","1813","1888","Pianist#Komponist#Klavierlehrer","","Augsburg#Budapest#Hamburg#Wien#Paris"},
				{"Egk, Werner","m","1901","1983","Komponist#Dirigent#Kapellmeister#Musikpädagoge#Kompositionslehrer#Textdichter","Verwalter#Professor","Augsburg#Berlin#Donauwörth#Frankfurt/Main#Gräfelfing#Indien#Inning/Ammersee#Italien#Paris#USA#München"},
				{"Führer, Robert Johann Nepomuk","m","1807","1861","Organist#Komponist#Kapellmeister#Chorleiter#Dirigent#Sänger#Kopist","","Augsburg#Braunau/Inn#Eggenfelden#Freising#Linz#München#Passau#Prag#Ried/Innkreis#Salzburg#Wien"},
				{"Widor, Charles-Marie","m","1844","1937","Organist#Komponist#Pianist#Dirigent#Orgellehrer#Musikpädagoge#Musikschriftsteller","Professor","Berlin#Brüssel#London#Madrid#München#Potsdam#Rom#Zürich#Paris"},
				{"Schulhoff, Erwin","m","1894","1942","Pianist#Komponist#Klavierlehrer#Musikpädagoge#Musikdokumentar","","Berlin#Brünn#Dresden#Köln#Leipzig#London#Ostrau#Paris#Saarbrücken#Weimar#Wien#Prag"},
				{"Bornefeld, Helmut","m","1906","1990","Komponist#Chorleiter#Organist#Pianist#Orgelsachverständiger#Sänger#Musikpädagoge","Schriftsteller#Professor","Stuttgart"},
				{"Dalayrac, Niclas","m","1753","1809","Komponist#Geiger#Sänger","Jurist","Deutschland#Paris"},
				{"Draeseke, Felix","m","1835","1913","Komponist#Pianist#Klavierlehrer#Kompositionslehrer#Textdichter#Musikredakteur","Rat","Berlin#Coburg#Frankreich#Genf#Italien#Lausanne#Leipzig#Luzern#München#Spanien#Weimar#Dresden"},
				{"Reutter, Hermann","m","1900","1985","Komponist#Kompositionslehrer#Musikpädagoge#Pianist#Musikalischer Leiter","Schulleiter","Baden-Baden#Braunschweig#Donaueschingen#Frankfurt/Main#Heilbronn#Japan#München#Stuttgart#USA"},
				{"Herzogenberg, Heinrich von","m","1843","1900","Komponist#Kompositionslehrer#Musikschriftsteller","Professor#Adeliger#Jurist","Berlin#Dresden#Feldkirch#Graz#Leipzig#München#Wien"},
				{"Roman, Johan Helmich","m","1694","1758","Komponist#Kapellmeister#Musikpädagoge#Veranstalter","","Augsburg#Berlin#Bologna#Dresden#Kassel#London#München#Neapel#Paris#Rom#Stockholm#Venedig#Wien"},
				{"Cramer, Johann Baptist","m","1771","1858","Pianist#Klavierlehrer#Komponist#Musikverleger","","Amsterdam#Berlin#Mannheim#München#Paris#Wien#London"},
				{"Benda, Franz","m","1709","1786","Komponist#Kapellmeister#Konzertmeister#Geiger#Bratscher#Tenor#Altist#Diskantist#Musikpädagoge#Geigenlehrer#Gesangslehrer#Chorknabe","","Bayreuth#Dresden#Prag#Warschau#Weimar#Wien#Potsdam"},
				{"Zumsteeg, Johann Rudolph","m","1760","1802","Komponist#Kapellmeister#Konzertmeister#Violoncellist#Musikpädagoge","Bildhauer","Stuttgart"},
				{"Chamberlain, Houston Stewart","m","1855","1927","Musikschriftsteller","Schriftsteller","Dresden#Genf#London#München#Stettin#Versailles#Wien#Bayreuth"},
				{"Bach, Johann Christoph Friedrich","m","1732","1795","Organist#Cembalist#Geiger#Komponist#Konzertmeister#Kapellmeister#Musikpädagoge","Jurist",""},
				{"Maximilian Emanuel","m","1662","1726","Gambist#Sänger#Tänzer#Mäzen","Fürst","Brüssel#Paris#Wien#München"},
				{"Lang, Hans","m","1897","1968","Komponist#Dirigent#Chorleiter#Organist#Musikpädagoge#Gesangslehrer","Soldat#Lehrer#Schulleiter","Eichstätt#Fürth#Köln#München#Nürnberg"},
				{"Pahlen, Kurt","m","1907","2003","Musikschriftsteller#Musikforscher#Kapellmeister#Dirigent#Musikkritiker#Komponist","Professor#Schulleiter#Intendant","Buenos Aires#Stuttgart#Wien#Zürich"},
				{"Mysliveček, Josef","m","1737","1781","Komponist#Geiger","Handwerker","Bologna#Florenz#Mailand#München#Neapel#Padua#Parma#Pavia#Prag#Rom#Turin#Venedig#Wien"},
				{"Ziehrer, Carl Michael","m","1843","1922","Komponist#Pianist#Dirigent#Kapellmeister","Handwerker","Berlin#Chicago#München#Wien"},
				{"Kozeluch, Leopold Anton","m","1747","1818","Komponist#Kapellmeister#Pianist#Musikpädagoge#Klavierlehrer","","Prag#Wien"},
				{"Kempff, Wilhelm Friedrich Walter","m","1895","1991","Pianist#Komponist#Organist#Musikpädagoge#Klavierlehrer#Musikalischer Leiter","","Berlin#Japan#Kanada#London#München#New York#Potsdam#Schweden#Stuttgart#Thurnau"},
				{"Crusius, Martin","m","1526","1607","Musikdokumentar#Lautenist#Cembalist","Lehrer#Philologe","Memmingen#Straßburg#Tübingen"},
				{"Lindpaintner, Peter Joseph von","m","1791","1856","Komponist#Dirigent#Kapellmeister#Bearbeiter#Geiger","","Aachen#Augsburg#London#München#Stuttgart"},
				{"Heinse, Wilhelm","m","1746","1803","Musikschriftsteller#Textdichter","Jurist#Bibliothekar#Schriftsteller#Professor","Aschaffenburg#Düsseldorf#Erfurt#Jena#Mainz#Rom"},
				{"Karl (2)","m","1697","1745","Lautenist","Kurfürst#Kaiser","München"},
				{"Muffat, Georg","m","1653","1704","Kapellmeister#Organist#Cembalist#Komponist#Geiger#Musikforscher","Diener","Augsburg#Ingolstadt#München#Paris#Passau#Prag#Rom#Salzburg#Wien"},
				{"Gabrieli, Andrea","m","1510","1586","Komponist#Organist#Sänger","","Augsburg#Frankfurt/Main#München#Tschechien#Venedig#Verona"},
				{"Kienzl, Wilhelm","m","1857","1941","Komponist#Pianist#Kapellmeister","Philosoph#Physiker","Amsterdam#Bad Aussee#Bayreuth#Graz#Hamburg#Leipzig#München#Schweiz#Weimar#Wien"},
				{"Carste, Hans","m","1909","1971","Dirigent#Pianist#Komponist#Chorleiter#Bearbeiter","Unternehmer","Breslau#Ostrau#Paris#Russland#Stockholm#Wien#Berlin"},
				{"Valentin, Karl","m","1882","1948","Unterhaltungskünstler#Zitherspieler#Sänger#Instrumentalist#Medienvertreter","Schauspieler#Schriftsteller","Berlin#Nürnberg#Wien#Zürich#München"},
				{"Birken, Sigmund von","m","1626","1681","Textdichter#Komponist","Schriftsteller#Lehrer#Graf#Übersetzer","England#Jena#Niederlande#Nürnberg#Rostock"},
				{"Ormandy, Eugene","m","1899","1985","Dirigent#Kapellmeister#Konzertmeister#Geiger#Geigenlehrer","","Australien#Berlin#Budapest#China#München#New York#Philadelphia"},
				{"Toscanini, Arturo","m","1867","1957","Dirigent#Violoncellist","Intendant","Bayreuth#Berlin#Bologna#Brüssel#Buenos Aires#Jerusalem#Kanada#London#Luzern#Mailand#New York#Paris#Parma#Salzburg#Turin#Venedig#Wien"},
				{"Kalbeck, Max","m","1850","1921","Musikschriftsteller#Textdichter#Geiger#Sänger#Komponist","Schriftsteller#Übersetzer#Journalist#Jurist","Breslau#München#Wien"},
				{"Wölfflin, Heinrich","m","1864","1945","","Professor#Kunstwissenschaftler","Basel#Berlin#München#Zürich"},
				{"Aiblinger, Johann Kaspar","m","1779","1867","Komponist#Kapellmeister#Chorleiter#Organist#Musikpädagoge#Musikaliensammler","","Landshut#Mailand#Tegernsee#Venedig#Vicenza#München"},
				{"Balde, Jacobus","m","1604","1668","Textdichter#Lautenist#Komponist","Schriftsteller#Geistlicher#Mönch#Professor#Historiker#Jurist","Amberg#Ingolstadt#Innsbruck#Landsberg#Landshut#München#Neuburg/Donau"},
				{"Chabrier, Emmanuel","m","1841","1894","Komponist#Chorleiter#Pianist#Musikpädagoge","Jurist#Beamter","Bayreuth#München#Spanien#Versailles#Paris"},
				{"Spee, Friedrich von","m","1591","1635","Textdichter","Theologe#Geistlicher#Dichter#Schriftsteller#Professor#Lehrer","Bamberg#Fulda#Köln#Mainz#Paderborn#Speyer#Trier#Würzburg"},
				{"Gulda, Friedrich","m","1930","2000","Pianist#Komponist","","Europa#Genf#München#Salzburg#Wien"},
				{"Carl (3)","m","1697","1718","","","Schweden"},
				{"Dohnányi, Ernst von","m","1877","1960","Komponist#Pianist#Dirigent#Klavierlehrer#Kompositionslehrer#Musikdokumentar","","Berlin#Bratislava#Budapest#Dänemark#Deutschland#Edinburgh#Frankreich#Italien#London#New York#Russland#Starnberg#Wien"},
				{"Knecht, Justin Heinrich","m","1752","1817","Komponist#Organist#Dirigent#Musikpädagoge#Musikschriftsteller#Veranstalter","Lehrer","Biberach#Stuttgart"},
				{"Carl (2)","m","1660","1697","","","Schweden"},
				{"Zingarelli, Nicola Antonio","m","1752","1837","Komponist#Kapellmeister#Dirigent#Musikpädagoge","","Loreto#Mailand#Neapel#Paris#Rom#Venedig"},
				{"Richter, Franz Xaver","m","1709","1789","Komponist#Kapellmeister#Bassist#Geiger#Kompositionslehrer#Musikschriftsteller#Bearbeiter","","Amsterdam#Bonn#Ettal#Italien#Kempten#London#Mannheim#Memmingen#München#Oettingen#Paris#Rastatt#Stuttgart#Ungarn#Wien#Straßburg"},
				{"Maazel, Lorin","m","1930","2014","Dirigent#Geiger","","Bayreuth#Berlin#London#München#New York#Paris#Wien"},
				{"Schiedermayr, Johann Baptist","m","1779","1840","Organist#Komponist#Kapellmeister#Musikpädagoge","","Linz#Passau#Schärding#Straubing#Windberg"},
				{"Abel, Carl Friedrich","m","1723","1787","Komponist#Gambist#Dirigent#Cembalist#Instrumentallehrer#Kompositionslehrer","","Dresden#Frankfurt/Main#Hamburg#Hannover#Leipzig#Ludwigslust#Mannheim#Paris#Potsdam#London"},
				{"Chausson, Ernest","m","1855","1899","Komponist#Pianist#Dirigent","Jurist#Schriftsteller#Maler","Bayreuth#München#Schweiz#Paris"},
				{"Torelli, Giuseppe","m","1658","1709","Komponist#Kapellmeister#Konzertmeister#Geiger#Bratscher#Musikpädagoge#Geigenlehrer","","Amsterdam#Ansbach#Berlin#Parma#Verona#Wien#Bologna"},
				{"Francisci, Erasmus","m","1627","1694","Musikschriftsteller","Gelehrter#Jurist#Verwalter#Rat#Schriftsteller","Nürnberg"},
				{"Rellstab, Ludwig","m","1799","1860","Musikschriftsteller#Textdichter#Komponist","Dichter#Offizier#Buchhändler","Bayreuth#Berlin#Bonn#Dresden#Frankfurt/Oder#Heidelberg#Italien#Schweiz#Weimar#Wien"},
				{"Bloch, Ernest","m","1880","1959","Komponist#Dirigent#Musikpädagoge","Professor","Brüssel#Frankfurt/Main#Genf#Lausanne#München#New York#Paris#San Francisco"},
				{"Einem, Gottfried von","m","1918","1996","Komponist#Dirigent#Musikdokumentar#Kompositionslehrer#Pianist","Intendant","Amerika#Bayreuth#Berlin#Dresden#England#Salzburg#Wien"},
				{"Popp, Lucia","w","1939","1993","Sopranist","","Bayreuth#Bratislava#Florenz#Frankfurt/Main#Genf#Graz#Hamburg#Karlsruhe#Köln#London#Mannheim#München#New York#Paris#Prag#Salzburg#Stuttgart#Wien#Zürich"},
				{"Kugler, Franz","m","1808","1858","Sänger","Kunstwissenschaftler#Maler#Schriftsteller#Historiker#Professor#Beamter","Berlin#Stettin"},
				{"Osiander, Lucas","m","1534","1604","Komponist#Orgelbauer#Orgelsachverständiger","Geistlicher#Theologe","Königsberg#Tübingen#Stuttgart"},
				{"Knab, Armin","m","1881","1951","Komponist#Pianist#Musikpädagoge#Kompositionslehrer","Jurist","Augsburg#Berlin#Fürth#Kitzingen#München#Vilshofen#Wien#Würzburg"},
				{"Küffner, Joseph","m","1776","1856","Komponist#Musikalischer Leiter#Geiger#Organist#Musikpädagoge#Geigenlehrer#Klavierlehrer#Bearbeiter#Musikdokumentar","Lehrer#Jurist","Brüssel#Niederlande#Paris#Würzburg"},
				{"Ruhland, Konrad","m","1932","2010","Chorleiter#Musikforscher#Musikpädagoge#Instrumentenkundler#Sänger#Gambist#Herausgeber#Musikverleger#Dirigent#Musikaliensammler","Lehrer","München#Passau#Niederalteich"},
				{"Mottl, Felix","m","1856","1911","Komponist#Dirigent#Kapellmeister#Pianist#Musikpädagoge#Sänger#Diskantist#Chorknabe","","Bayreuth#Karlsruhe#München#New York#Weimar#Wien"},
				{"Döllinger, Ignaz","m","1799","1890","Sänger#Musikalischer Leiter","Professor#Geistlicher#Theologe","Aschaffenburg#Bamberg#Frankfurt/Main#Rom#Scheinfeld#Würzburg#München"},
				{"Kálmán, Emmerich","m","1882","1953","Komponist#Pianist#Musikschriftsteller","Jurist","Berlin#Budapest#England#Frankfurt/Main#München#New York#Paris#Stuttgart#Wien#Zürich"},
				{"Klemperer, Otto","m","1885","1973","Dirigent#Kapellmeister#Chorleiter#Komponist#Pianist#Musikschriftsteller","","München"},
				{"Oswald von Wolkenstein","m","1377","1445","Minnesänger","Schriftsteller#Ritter#Dichter#Rat#Jurist","Avignon#Basel#Bratislava#Jerusalem#Konstanz#München#Nürnberg#Paris#Parma#Portugal#Spanien#Ungarn#Venedig"},
				{"Behrend, Siegfried","m","1933","1990","Gitarrist#Komponist#Instrumentallehrer#Dirigent","","Berlin#Italien#Leipzig#Riedenburg#Spanien"},
				{"Wunderlich, Fritz","m","1930","1966","Tenor#Unterhaltungskünstler#Hornist#Trompeter#Harmonikaspieler#Pianist","","Aix-en-Provence#Berlin#Buenos Aires#Edinburgh#Frankfurt/Main#Frankreich#Freiburg/Breisgau#Kaiserslautern#London#München#Niederlande#Salzburg#Schweiz#Schwetzingen#Stuttgart#Venedig#Wien"},
				{"Kogel, Gustav Friedrich","m","1849","1921","Dirigent#Kapellmeister#Komponist#Musikpädagoge","","Aachen#Frankfurt/Main#Frankreich#Kassel#Köln#Leipzig#Nürnberg"},
				{"Griesbacher, Peter","m","1864","1933","Komponist#Musikpädagoge#Musikschriftsteller#Glockensachverständiger#Herausgeber","","Frankfurt/Main#Passau#Regensburg#Walderbach"},
				{"Martius, Carl Friedrich Philipp von","m","1794","1868","Musikforscher#Geiger","Gelehrter#Mediziner","Brasilien#Erlangen#Landshut#München"},
				{"Mühsam, Erich","m","1878","1934","Unterhaltungskünstler#Textdichter","Schriftsteller#Schauspieler","München"},
				{"Schroeder, Hermann","m","1904","1984","Komponist#Organist#Musikpädagoge#Kompositionslehrer#Musikalischer Leiter#Musikforscher","","Innsbruck#Köln#Regensburg#Trier"},
				{"Clemens non Papa, Jacobus","m","1510","1556","Komponist#Sänger","",""},
				{"Benz, Richard","m","1884","1966","Musikschriftsteller","Schriftsteller#Kulturwissenschaftler#Kunstwissenschaftler#Historiker#Philologe#Gelehrter","Dresden#Freiburg/Breisgau#Leipzig#München#Heidelberg"},
				{"Hertel, Johann Wilhelm","m","1727","1789","Komponist#Musikforscher#Geiger#Cembalist#Pianist#Organist#Konzertmeister#Musikpädagoge","Verwalter#Rat","Berlin#Hamburg#Ludwigslust#Schwerin#Stralsund"},
				{"Gál, Hans","m","1890","1987","Komponist#Musikpädagoge#Musikforscher#Pianist#Chorleiter#Dirigent#Musikschriftsteller","Schulleiter#Bibliothekar#Soldat","Edinburgh#Mainz#Wien"},
				{"Bidermann, Jakob","m","1578","1639","Musikschriftsteller","Theologe","Dillingen/Donau#Landsberg#Rom"},
				{"Xylander, Wilhelm","m","1532","1576","Musiker","Gelehrter#Philologe#Lehrer","Heidelberg"},
				{"Wellesz, Egon Joseph","m","1885","1974","Komponist#Musikforscher#Herausgeber#Musikpädagoge#Musikredakteur#Musikkritiker#Musikschriftsteller","Historiker#Kunstwissenschaftler#Kulturwissenschaftler#Jurist#Professor","Niederlande#Wien"},
				{"Righini","m","1794","1796","Kapellmeister","","Berlin"},
				{"Hérold, Ferdinand","m","1791","1833","Komponist#Pianist","","Mailand#München#Neapel#Rom#Turin#Venedig#Wien#Paris"},
				{"Kubelík, Rafael","m","1914","1996","Dirigent#Komponist","","Amsterdam#Brünn#Chicago#London#Luzern#München#New York#Prag#Wien"},
				{"Einstein, Alfred","m","1880","1952","Musikforscher#Musikredakteur#Musikpädagoge#Musikschriftsteller#Instrumentenkundler","","Berlin#London#München#New York"},
				{"Mitterer, Ignaz Martin","m","1850","1924","Organist#Komponist#Dirigent","","Rom#Regensburg"},
				{"Salmen, Walter","m","1926","2013","Musikforscher#Musikschriftsteller","Professor","Freiburg/Breisgau#Heidelberg#Innsbruck#Israel#Kiel#Münster#Saarbrücken#Schweiz#USA"},
				{"Krol, Bernhard","m","1920","2013","Hornist#Komponist","Professor","Bayreuth#Berlin#Wien#Stuttgart"},
				{"Acker, Dieter","m","1940","2006","Komponist#Kompositionslehrer","Professor","Darmstadt#Düsseldorf#München"},
				{"Sterkel, Johann Franz Xaver","m","1750","1817","Komponist#Kapellmeister#Dirigent#Pianist#Organist","Theologe","Aschaffenburg#Florenz#Mainz#München#Neapel#Regensburg#Rom#Venedig#Würzburg"},
				{"Ludwig (3)","m","1786","1868","Mäzen","König#Historiker#Schriftsteller#Architekt","Göttingen#Landshut#Rom#Würzburg#München"},
				{"Gerbert, Martin","m","1720","1793","Musikschriftsteller","","Bologna#Freiburg/Breisgau#München#Paris#Regensburg#Rom#Salzburg#St. Blasien#St. Gallen#Straßburg#Tegernsee#Wien"},
				{"Hauptmann, Moritz","m","1792","1868","Geiger#Komponist#Musikforscher#Musikredakteur#Musikpädagoge#Kompositionslehrer#Gesangslehrer#Chorleiter#Organist","","Berlin#Dresden#Genf#Göttingen#Halle#Kassel#Leipzig#Moskau#Odessa#Poltawa#St. Petersburg#Stockholm#Wien"},
				{"Cyprianus, Ernst Salomon","m","1673","1745","Musikschriftsteller","Theologe",""},
				{"Werner, Gregor Joseph","m","1693","1766","Komponist#Kapellmeister#Dirigent#Organist","","Wien#Eisenstadt"},
				{"Chrysander, Friedrich","m","1826","1901","Musikforscher#Herausgeber#Musikredakteur#Musikkritiker","Philosoph","Hamburg#London#Rostock"},
				{"Croft, William","m","1678","1727","Organist#Komponist#Musikpädagoge#Chorknabe","","London"},
				{"Weigel, Erhard","m","1625","1699","Musikschriftsteller","Arzt#Mathematiker#Pädagoge#Philosoph#Professor#Rat","Dänemark#Leipzig#Regensburg#Schweden#Wunsiedel#Jena"},
				{"Romberg, Bernhard","m","1767","1841","Violoncellist#Komponist#Musikpädagoge","","Berlin#Hamburg#Münster#Paris#Russland#Spanien"},
				{"Karl Ludwig","m","1648","1680","","","Heidelberg"},
				{"Celtis, Konrad","m","1459","1508","Musikdokumentar#Textdichter","Schriftsteller#Geisteswissenschaftler#Professor#Lehrer#Bibliothekar#Gelehrter","Bologna#Budapest#Erfurt#Florenz#Hamburg#Heidelberg#Ingolstadt#Köln#Krakau#Kroatien#Leipzig#Lübeck#Lüneburg#Magdeburg#Nürnberg#Österreich#Padua#Prag#Regensburg#Rom#Rostock#Schlesien#Ungarn#Venedig#Wien"},
				{"Legrand, Wilhelm","m","1769","1845","Kapellmeister#Oboist#Komponist#Bearbeiter#Instrumentalist#Musikpädagoge#Klarinettist","Beamter","Zweibrücken#München"},
				{"Berry, Walter","m","1929","2000","Bassist#Bariton","","Aix-en-Provence#Barcelona#Berlin#Brüssel#Buenos Aires#Chicago#London#Mailand#Moskau#München#New York#Paris#Salzburg#San Francisco#Stuttgart#Wien"},
				{"Gregor, Joseph","m","1888","1960","Textdichter#Musikforscher","Kunstwissenschaftler#Philosoph#Regisseur#Bibliothekar#Professor","Berlin#Czernowitz#Europa#München#USA#Wien"},
				{"Karl Philipp","m","1661","1742","Mäzen","Adliger","Heidelberg#Mannheim"},
				{"Indy, Vincent d&apos;&apos;","m","1851","1931","Komponist#Dirigent#Chorleiter#Musikpädagoge#Kompositionslehrer#Musikforscher#Musikschriftsteller#Pauker#Organist","Ritter#Soldat","Aachen#Algerien#Barcelona#Basel#Bayreuth#Brüssel#Dresden#England#Estland#Italien#Kanada#Karlsruhe#Köln#Leipzig#Lettland#Linz#Lyon#Moskau#München#Niederlande#Nürnberg#Polen#Rumänien#Salzburg#Schweiz#Tirol#Tutzing#Ungarn#Weimar#Wien#Paris"},
				{"Fricsay, Ferenc","m","1914","1963","Dirigent","","Berlin#Budapest#München#Salzburg#Schweiz#Wien"},
				{"Freher, Marquard","m","1565","1614","Musikschriftsteller","Jurist#Historiker","Altdorf#Basel#Heidelberg"},
				{"Call, Leonhard von","m","1767","1815","Komponist#Gitarrist","Beamter","Wien"},
				{"Haller, Michael","m","1840","1915","Organist#Komponist#Chorleiter#Musikpädagoge","Pfarrer","Metten#Regensburg"},
				{"Dietrich, Marlene","w","1901","1992","Sänger#Geiger#Pianist","Schauspieler","Aachen#Afrika#Baden-Baden#Berlin#Düsseldorf#Israel#London#New York#Paris#Pilsen#Polen#Warschau#Weimar"},
				{"Paumgartner, Bernhard","m","1887","1971","Komponist#Musikschriftsteller#Dirigent#Musikforscher#Herausgeber","Jurist#Professor","Florenz#Wien#Salzburg"},
				{"Niemann, Walter Rudolph","m","1876","1953","Komponist#Pianist#Musikpädagoge#Musikdokumentar#Musikforscher#Musikschriftsteller","","Leipzig"},
				{"Jochum, Eugen (2)","m","1902","1987","Dirigent#Kapellmeister#Chorleiter#Pianist#Organist#Musikdokumentar","","Amsterdam#Augsburg#Babenhausen#Bamberg#Bayreuth#Berlin#Duisburg#Edinburgh#Hamburg#Kiel#Lübeck#Luzern#Mannheim#München#New York#Rom"},
				{"Eccard, Johannes","m","1553","1611","Komponist#Kapellmeister#Sänger#Chorknabe","","Ansbach#Augsburg#Berlin#Erfurt#Mühlhausen/Thüringen#München#Weimar"},
				{"Vignola, Jacomo","m","1507","1573","","Architekt","Rom"},
				{"Carl Gustaf","m","1654","1660","","","Schweden"},
				{"Konrad","m","1225","1287","Minnesänger","Schriftsteller","Straßburg#Würzburg#Basel"},
				{"Kraus, Eberhard","m","1931","2003","Organist#Cembalist#Musikpädagoge#Orgelsachverständiger#Musikverleger#Komponist","","Jerusalem#München#Rom#Regensburg"},
				{"Schmid, Ernst Fritz","m","1904","1960","Musikforscher#Bratscher#Geiger#Dirigent#Musikschriftsteller","Professor#Biologe","Amorbach#Augsburg#Düsseldorf#Freiburg/Breisgau#Göttingen#Graz#Miltenberg#München#Salzburg#Tübingen#Wien"},
				{"Kaminski, Heinrich","m","1886","1946","Komponist#Pianist#Kompositionslehrer#Musikschriftsteller","Bankkaufmann#Wirtschaftswissenschaftler#Professor","Berlin#Bielefeld#Heidelberg#Kochel"},
				{"Fischer, Johann Caspar Ferdinand","m","1665","1746","Komponist#Kapellmeister","","Augsburg#Rastatt"},
				{"Türk, Daniel Gottlob","m","1750","1813","Komponist#Musikpädagoge#Organist#Chorleiter#Dirigent#Sänger#Musikschriftsteller","","Dresden#Halle#Leipzig"},
				{"Ludwig (4)","m","1845","1886","Mäzen","König","München"},
				{"Benatzky, Ralph","m","1884","1957","Textdichter#Komponist#Unterhaltungskünstler#Sänger","Offizier#Philologe#Schriftsteller","Berlin#München#Prag#Wien#Zürich"},
				{"Saubert, Johann","m","1592","1646","Musikschriftsteller","Geistlicher#Theologe","Nürnberg"},
				{"Nägeli, Hans Georg","m","1773","1836","Komponist#Musikschriftsteller#Musikalienhändler#Musikverleger#Sänger#Gesangslehrer#Chorleiter#Dirigent","Verleger","Bremen#Frankreich#Zürich"},
				{"Erk, Ludwig","m","1807","1883","Volksliedsammler#Chorleiter#Dirigent#Musikforscher#Musikpädagoge#Gesangslehrer#Komponist","","Offenbach/Main#Berlin"},
				{"Zechlin, Ruth","w","1926","2007","Komponist#Organist#Pianist#Musikpädagoge#Kompositionslehrer#Cembalist#Dirigent","Professor","Berlin#Leipzig#Passau"},
				{"Rottmanner, Eduard","m","1809","1843","Komponist#Kapellmeister#Organist#Pianist#Geiger#Klarinettist#Gitarrist#Tenor#Gesangslehrer#Musikpädagoge","","München#Nürnberg#Speyer"},
				{"Wolzogen und Neuhaus, Hans Paul von","m","1848","1938","Textdichter#Herausgeber","Philosoph#Journalist","Berlin#Bayreuth"},
				{"Neidhart von Reuental","m","1170","1240","Minnesänger","","Geisenhausen#Landshut#Steiermark#Wien"},
				{"Dingelstedt, Franz von","m","1814","1881","Musiktheaterregisseur","Intendant#Regisseur#Schriftsteller#Übersetzer#Theologe","Fulda#Jena#Kassel#London#Marburg#München#Paris#Stuttgart#Weimar#Wien"},
				{"Schede Melissus, Paulus","m","1539","1602","Organist#Chorleiter#Musikpädagoge","Schriftsteller#Adliger#Lehrer#Übersetzer","Augsburg#Erfurt#Genf#Heidelberg#Jena#Königsberg#Leipzig#Lyon#Nürnberg#Prag#Schweiz#Speyer#Wien#Wittenberg#Würzburg#Zwickau"},
				{"Sandrart, Joachim von","m","1606","1688","","Maler#Schriftsteller#Übersetzer","Amsterdam#England#Frankfurt/Main#Nürnberg#Prag#Rom#Salzburg#Wien"},
				{"Jahn, Otto","m","1813","1869","Musikforscher#Komponist","Historiker#Philologe#Professor","Bonn#Florenz#Greifswald#Kiel#Leipzig#Paris#Rom#Wien"},
				{"Sinding, Christian August","m","1856","1941","Komponist#Kompositionslehrer#Instrumentalist","Professor","Berlin#Dresden#Leipzig#London#München#New York"},
				{"Lechner, Leonhard","m","1553","1606","Komponist#Kapellmeister#Dirigent#Herausgeber#Sängerknabe","","Altdorf#Dresden#Italien#Landshut#München#Nürnberg#Tübingen#Stuttgart"},
				{"Pisendel, Johann Georg","m","1687","1755","Geiger#Konzertmeister#Komponist#Musikpädagoge","","Ansbach#Darmstadt#Frankreich#Leipzig#Venedig#Weimar#Dresden"},
				{"Stanford, Charles Villiers","m","1852","1924","Komponist#Dirigent#Pianist#Organist","Professor","Berlin#Hamburg#Leipzig#London"},
				{"Frick, Gottlob","m","1906","1994","Bassist","","Amsterdam#Barcelona#Bayreuth#Berlin#Brüssel#Coburg#Dresden#Edinburgh#Florenz#Freiburg/Breisgau#Hamburg#Königsberg#London#Mailand#München#New York#Paris#Rom#Salzburg#Stuttgart#Wien"},
				{"Holzbauer, Ignaz Jakob","m","1711","1783","Komponist#Kapellmeister#Sänger#Geiger","Verwalter#Rat","Bologna#Florenz#Ljubljana#Mailand#Paris#Rom#Schwetzingen#Stuttgart#Turin#Venedig#Wien#Mannheim"},
				{"Volkmann, Robert","m","1815","1883","Komponist#Chorleiter#Organist#Pianist#Musikpädagoge#Musikdokumentar#Sänger#Chorknabe","","Berlin#Freiberg#Leipzig#Prag#Wien#Budapest"},
				{"Koetsier, Jan","m","1911","2006","Dirigent#Komponist#Pianist#Korrepetitor#Musikpädagoge","","Amsterdam#Berlin#Lübeck#München"},
				{"Hotter, Hans","m","1909","2003","Bariton#Bassist#Organist#Chorleiter#Gesangslehrer","Philosoph#Regisseur","Amsterdam#Australien#Barcelona#Bayreuth#Breslau#Brüssel#Buenos Aires#Chicago#Edinburgh#Florenz#Hamburg#Japan#London#Mailand#New York#Offenbach/Main#Paris#Prag#Salzburg#San Francisco#Stuttgart#Wien#München"},
				{"Wagenseil, Johann Christoph","m","1633","1708","Musikforscher","Schulleiter#Philologe#Jurist#Lehrer#Bibliothekar#Historiker","Afrika#England#Frankreich#Greifswald#Italien#Niederlande#Nürnberg#Rostock#Spanien#Stockholm#Altdorf"},
				{"Westenrieder, Lorenz von","m","1748","1829","Musikschriftsteller","Schriftsteller#Historiker#Theologe#Pfarrer#Professor","Freising#Landshut#München"},
				{"Weigl, Joseph (2)","m","1766","1846","Komponist#Dirigent#Kapellmeister#Pianist#Gesangslehrer#Sänger","","Mailand#Wien"},
				{"Monte, Philippe de","m","1521","1603","Komponist#Kapellmeister#Dirigent#Musikpädagoge","Journalist","England#Neapel#Rom#Wien"},
				{"Winkler, Gerhard","m","1906","1977","Komponist#Pianist#Chorknabe","","Kempten#München#Berlin"},
				{"Crüger, Johann","m","1598","1663","Komponist#Textdichter#Musikschriftsteller#Kapellmeister#Chorleiter#Dirigent#Organist#Musikpädagoge#Bassist","Lehrer","Bratislava#Breslau#Österreich#Regensburg#Ungarn#Wittenberg#Berlin"},
				{"Hasius, Johann Matthias","m","1684","1742","Musiker","Mathematiker","Wittenberg"},
				{"Sperger, Johannes Matthias","m","1750","1812","Kontrabassist#Komponist#Organist#Kopist","","Ansbach#Berlin#Bratislava#Brünn#Dresden#Eisenstadt#Leipzig#Lübeck#Parma#Passau#Prag#Schwerin#Triest#Wien#Ludwigslust"},
				{"Lewald, Johann August","m","1793","1872","Musikredakteur#Musikschriftsteller","Schriftsteller#Beamter#Schauspieler#Journalist","Bamberg#Breslau#Brünn#Frankreich#Hamburg#Italien#München#Nürnberg#Paris#Polen#Stuttgart#Tirol"},
				{"Schnabel, Artur","m","1882","1951","Pianist#Musikpädagoge#Klavierlehrer#Komponist","","New York#Russland#Wien#Berlin"},
				{"Burkhard, Willy","m","1900","1955","Komponist#Chorleiter#Kompositionslehrer#Veranstalter","","Bern#Leipzig#München#Paris#Zürich"},
				{"Kerll, Johann Kaspar","m","1625","1693","Komponist#Kapellmeister#Organist#Chorleiter#Musikpädagoge#Instrumentallehrer#Klavierlehrer","Rat","Adorf#Brüssel#Dresden#München#Prag#Regensburg#Rom#Wien"},
				{"Lachner, Ignaz","m","1807","1895","Komponist#Geiger#Pianist#Organist#Dirigent#Kapellmeister","","Frankfurt/Main#Hamburg#München#Stockholm#Stuttgart#Wien"},
				{"Vetter, Conrad","m","1546","1622","Textdichter","Pfarrer#Geistlicher#Schriftsteller#Lehrer","Hall/Tirol#Ingolstadt#München#Regensburg"},
				{"Wolzogen, Ernst von","m","1855","1934","Komponist#Unterhaltungskünstler","Schriftsteller#Soldat","Berlin#Darmstadt#Leipzig#München#Straßburg"},
				{"Rein, Walter","m","1893","1955","Komponist#Musikethnologe","Lehrer#Professor","Frankfurt/Main#Hof#Kassel#Weimar#Berlin"},
				{"Gassmann, Florian Leopold","m","1729","1774","Komponist#Harfenist#Chorleiter#Dirigent#Kompositionslehrer#Veranstalter","","Bologna#Karlsbad#Rom#Venedig#Wien"},
				{"Rochlitz, Johann Friedrich","m","1769","1842","Musikredakteur#Musikschriftsteller","","Leipzig"},
				{"Zeltner, Gustav Georg","m","1672","1738","Musikschriftsteller#Musikpädagoge","Geistlicher#Theologe#Lehrer#Professor","Altdorf#Fürth#Nürnberg"},
				{"Müller-Blattau, Joseph Maria","m","1895","1976","Musikforscher#Organist#Pianist#Dirigent#Komponist","Professor#Lehrer#Soldat","Frankfurt/Main#Freiburg/Breisgau#Kirchheimbolanden#Straßburg"},
				{"Eder, Victor","m","1863","1933","Musikdokumentar","","Metten"},
				{"Menschick, Wolfram","m","1937","2010","Komponist#Dirigent#Organist#Glockensachverständiger#Musikpädagoge","Professor","Amberg#Eichstätt#München#Regensburg#Straubing"},
				{"Baumgartner, August","m","1814","1862","Komponist#Dirigent#Musikforscher#Organist#Pianist#Chorleiter#Musikschriftsteller","","München"},
				{"Armstrong, Louis Daniel","m","1901","1971","Trompeter#Sänger#Komponist#Textdichter#Musikalischer Leiter","Schauspieler","Chicago#New York"},
				{"Feyerabend, Sigmund","m","1527","1590","Notendrucker","Drucker#Verleger","Frankfurt/Main"},
				{"Schock, Rudolf Johann","m","1915","1986","Tenor#Unterhaltungskünstler","","Australien#Bayreuth#Berlin#Braunschweig#Duisburg#Düsseldorf#Edinburgh#Hamburg#Hannover#Köln#London#München#Salzburg#Wien"},
				{"Aventinus, Johannes","m","1477","1534","Musikdokumentar#Musikpädagoge#Komponist","Historiker#Lehrer","Augsburg#Ingolstadt#Italien#Krakau#Paris#Regensburg#Wien#München"},
				{"Cavalli, Francesco","m","1602","1676","Komponist#Kapellmeister#Organist#Tenor#Musikpädagoge#Cembalist#Diskantist#Chorknabe","","Innsbruck#Mailand#München#Paris#Venedig"},
				{"Böhm, Theobald","m","1794","1881","Flötenbauer#Flötist#Komponist","Handwerker","London#Paris#München"},
				{"Weiss, Silvius Leopold","m","1686","1750","Lautenist#Komponist","","Berlin#Breslau#Dresden#Düsseldorf#Leipzig#München#Prag#Rom#Wien"},
				{"Rothenberger, Anneliese","w","1924","2010","Sopranist","Schauspieler#Schriftsteller","Duisburg#Düsseldorf#Edinburgh#Glyndebourne#Hamburg#Koblenz#Mailand#Mannheim#New York#Salzburg#Wien#Zürich"},
				{"Frommel, Gerhard","m","1906","1984","Kapellmeister#Dirigent#Komponist#Geiger#Pianist#Musikpädagoge#Kompositionslehrer","","Berlin#Darmstadt#Essen#Frankfurt/Main#Heidelberg#Karlsruhe#Leipzig#München#Trossingen"},
				{"Weismann, Julius","m","1879","1950","Komponist#Pianist#Dirigent#Musikpädagoge#Kompositionslehrer#Klavierlehrer","","Berlin#Lausanne#München#Freiburg/Breisgau"},
				{"Vinci, Leonardo","m","1690","1730","Komponist#Textdichter#Kapellmeister#Dirigent","",""},
				{"Bellman, Carl Michael","m","1740","1795","Komponist#Zupfinstrumentenspieler#Sänger#Textdichter","Schriftsteller#Schauspieler#Übersetzer","Uppsala#Stockholm"},
				{"Marpurg, Friedrich Wilhelm","m","1718","1795","Musikschriftsteller#Komponist#Musikalischer Leiter","Sekretär","Berlin#Halle#Paris"},
				{"Raucheisen, Michael","m","1889","1984","Pianist#Organist#Geiger#Bratscher#Musikalischer Leiter#Bearbeiter#Komponist#Musikschriftsteller","Professor","Bern#München#New York#Berlin"},
				{"Mach, Ernst","m","1838","1916","Musikforscher","Physiker#Professor#Historiker","Graz#Prag#Wien"},
				{"Maderna, Bruno","m","1920","1973","Dirigent#Komponist#Geiger#Musikpädagoge#Veranstalter","","Darmstadt#München#Paris#Rom#Salzburg#Siena#Venedig#Mailand"},
				{"Pavarotti, Luciano","m","1935","2007","Tenor#Gesangslehrer","Lehrer","Amsterdam#Australien#Barcelona#Chicago#Glyndebourne#Hamburg#London#Mailand#Neapel#New York#Paris#Philadelphia#Polen#Rom#Salzburg#San Francisco#Spanien#Ungarn#Verona#Wien#Zürich"},
				{"Ehmann, Wilhelm","m","1904","1989","Musikforscher#Musikpädagoge#Organist#Chorleiter#Dirigent#Herausgeber#Komponist#Bearbeiter#Sänger#Trompeter","Lehrer#Professor#Kunstwissenschaftler#Philosoph#Soldat","Baden-Baden#Berlin#Bielefeld#Innsbruck#Leipzig#München#Münster#Freiburg/Breisgau"},
				{"Schillings, Max von","m","1868","1933","Komponist#Dirigent#Chorleiter#Musikpädagoge#Korrepetitor","Intendant#Adliger#Soldat","Bayreuth#Berlin#Bonn#Heidelberg#München#Riga#Stuttgart#Tübingen#USA#Zoppot"},
				{"Maximilian Joseph","m","1756","1825","Mäzen","Soldat#Herzog#Kurfürst#König","Ansbach#Landau/Pfalz#Mannheim#Paris#Zweibrücken#München"},
				{"Murr, Christoph Gottlieb von","m","1733","1811","Musikschriftsteller","Jurist#Schriftsteller#Philologe#Historiker#Kulturwissenschaftler#Kunstwissenschaftler#Mathematiker#Übersetzer","Altdorf#Amsterdam#Hamburg#London#Padua#Straßburg#Venedig#Vicenza#Wien#Nürnberg"},
				{"Trajetta, Tommaso Michele Francesco Saverio","m","1727","1779","Komponist#Kapellmeister#Dirigent#Musikpädagoge#Gesangslehrer","Intendant","London#Mailand#Mannheim#München#Neapel#Padua#Paris#Parma#Rom#St. Petersburg#Venedig#Wien"},
				{"Suitner, Otmar","m","1922","2010","Dirigent#Pianist","Professor","Aix-en-Provence#Bayreuth#Berlin#Dresden#Griechenland#Innsbruck#Moskau#München#Prag#Rom#Salzburg#San Francisco#Schweden#Schweiz#Wien"},
				{"Cannabich, Johann Christian Innozenz Bonaventura","m","1731","1798","Komponist#Geiger#Konzertmeister#Kapellmeister#Dirigent","","Mailand#München#Paris#Rom#Stuttgart#Wien#Mannheim"},
				{"Mauersberger, Rudolf","m","1889","1971","Komponist#Organist#Pianist#Dirigent#Chorleiter#Herausgeber","Soldat#Lehrer#Professor","Aachen#Berlin#Dresden#Leipzig#Marburg#Niederlande#USA"},
				{"Doppelmayr, Johann Gabriel","m","1671","1750","Musikdokumentar","Mathematiker#Lehrer#Professor","Nürnberg"},
				{"Greith, Karl","m","1828","1887","Komponist#Kapellmeister#Dirigent#Organist#Chorleiter#Orgellehrer#Musikpädagoge","Professor","Augsburg#Frankfurt/Main#München#St. Gallen"},
				{"Albrecht, Gerd","m","1935","2014","Dirigent","Intendant","Berlin#Buenos Aires#Edinburgh#Hamburg#Japan#Kassel#Kiel#Kopenhagen#Lübeck#Luzern#Mainz#München#Prag#Salzburg#Stuttgart#Wien#Zürich"},
				{"Knef, Hildegard","w","1925","2002","Sänger#Textdichter#Unterhaltungskünstler","Schauspieler#Schriftsteller","Berlin#New York"},
				{"Dalberg, Karl Theodor","m","1744","1817","Musikschriftsteller","Kurfürst#Freiherr#Politiker#Bischof#Mönch#Schriftsteller","Erfurt#Frankfurt/Main#Konstanz#Mainz#Regensburg"},
				{"Scherchen, Hermann","m","1891","1966","Dirigent#Bratscher#Musikpädagoge#Herausgeber","","Bayreuth#Berlin#Darmstadt#Frankfurt/Main#Hannover#Köln#Königsberg#Leipzig#München#Palermo#Riga#Weikersheim#Wien#Winterthur"},
				{"Rühmann, Heinz","m","1902","1994","Unterhaltungskünstler#Sänger","Schauspieler","Berlin#Bremen#Breslau#Hannover#München"},
				{"Schmeller, Johann Andreas","m","1785","1852","Volksliedsammler","Lehrer#Soldat#Bibliothekar#Professor#Sprachwissenschaftler","Schweiz#Spanien#München"},
				{"Ansermet, Ernest","m","1883","1969","Dirigent","Mathematiker#Lehrer","Berlin#Buenos Aires#Genf#London#München#Paris#Russland#USA"},
				{"Erdmann, Dietrich","m","1917","2009","Komponist#Chorleiter#Violoncellist#Musikpädagoge","Professor#Schulleiter","Berlin"},
				{"Schenk, Erich","m","1902","1974","Musikforscher#Musikpädagoge#Musikredakteur#Musikalischer Leiter","Professor","Berlin#Brünn#Italien#München#Rostock#Salzburg#Wien"},
				{"Karl Alexander","m","1736","1806","","","Ansbach#Bayreuth"},
				{"Ernst","m","1818","1893","Komponist","Herzog","Coburg"},
				{"Ferdinand Maria","m","1636","1679","Mäzen","Kurfürst","München"},
				{"Kutzer, Ernst Ludwig","m","1918","2008","Komponist#Musikpädagoge#Organist","Lehrer","Amberg#Bad Abbach#Bärnau#Mitterteich#München#Regensburg#Tirschenreuth#Waldsassen"},
				{"Fellerer, Karl Gustav","m","1902","1984","Musikforscher#Pianist#Organist","Professor#Schulleiter","Berlin#Freiburg/Üechtland#München#Münster#Regensburg#Köln"},
				{"Lemacher, Heinrich","m","1891","1966","Komponist#Musikforscher#Musikschriftsteller#Organist#Chorleiter#Dirigent","Professor","Bonn#Köln"},
				{"Heger, Robert","m","1886","1978","Dirigent#Kapellmeister#Violoncellist","","Bayreuth#Berlin#Kassel#London#Lyon#München#Nürnberg#Straßburg#Ulm#Wien#Wuppertal#Zoppot#Zürich"},
				{"Möckl, Franz","m","1925","2014","Chorleiter#Komponist#Klarinettist#Musikpädagoge#Herausgeber#Veranstalter","Lehrer#Offizier","Berlin#Coburg#Eger#Erlangen#Nürnberg"},
				{"Willaert, Adrian","m","1480","1562","Komponist#Kapellmeister#Sänger","","Mailand#Paris#Venedig"},
				{"Johann Wilhelm","m","1658","1716","Mäzen","Kurfürst#Herzog","London#Neapel#Paris#Rom#Turin#Venedig#Wien#Düsseldorf"},
				{"Toch, Ernst","m","1887","1964","Komponist#Pianist#Musikforscher#Musikpädagoge#Kompositionslehrer#Dirigent","","Baden-Baden#Berlin#Donaueschingen#Florenz#Frankfurt/Main#Heidelberg#London#Mannheim#München#New York#Paris#Wien#Zürich"},
				{"Künneke, Eduard","m","1885","1953","Komponist#Chorleiter#Dirigent#Kapellmeister#Musikforscher","","Dresden#London#Mannheim#München#New York#Potsdam#Berlin"},
				{"Schünemann, Georg","m","1884","1945","Musikforscher#Herausgeber","Professor","Berlin"},
				{"Woll, Erna","w","1917","2005","Komponist#Pianist#Organist#Chorleiter#Musikpädagoge#Musikforscher#Musikschriftsteller","Philologe","Basel#Heidelberg#Köln#München#Weißenhorn#Augsburg"},
				{"Celibidache, Sergiu","m","1912","1996","Dirigent#Musikpädagoge#Musikforscher#Komponist#Kompositionslehrer#Pianist","","Berlin#Buenos Aires#Köln#Kopenhagen#London#Mailand#Mainz#München#Paris#Philadelphia#Siena#Stockholm#Stuttgart#Turin#Venedig"},
				{"Thuille, Ludwig Wilhelm Andreas Maria","m","1861","1907","Komponist#Pianist#Chorleiter#Sänger#Musikpädagoge#Klavierlehrer#Kompositionslehrer#Chorknabe","","Innsbruck#München"},
				{"Lambert, Johann Heinrich","m","1728","1777","Musikdokumentar","Physiker#Ingenieur#Lehrer#Rat","Basel#Berlin#Chur#Frankreich#Italien#München#Niederlande"},
				{"Schuster, Joseph","m","1748","1812","Kapellmeister#Dirigent#Komponist","","Dresden"},
				{"Krieger, Johann Philipp","m","1649","1725","Komponist#Kapellmeister#Dirigent#Organist#Cembalist","","Bayreuth#Bologna#Braunschweig#Dresden#Florenz#Frankfurt/Main#Halle#Kassel#Kopenhagen#Neapel#Nürnberg#Padua#Rom#Venedig#Weißenfels#Wien"},
				{"Herrmann, Hugo","m","1896","1967","Komponist#Organist#Pianist#Sänger#Chorleiter#Dirigent#Musikpädagoge","Lehrer#Professor#Soldat","Berlin#Donaueschingen#Frankfurt/Main#Ludwigsburg#Mannheim#Schwäbisch Gmünd#Stuttgart#Trossingen#Wiesbaden#Würzburg"},
				{"Kobell, Franz von","m","1803","1882","Volksliedsammler#Textdichter#Zitherspieler#Herausgeber","Geologe#Naturwissenschaftler#Schriftsteller#Professor","Erlangen#Landshut#Paris#München"},
				{"Tscherepnin, Alexander","m","1899","1977","Komponist#Pianist#Musikpädagoge","Professor","Chicago#München#New York#Paris"},
				{"Freigius, Johann Thomas","m","1576","1583","Musikdokumentar#Musikpädagoge","Schulleiter#Lehrer#Jurist","Altdorf"},
				{"Flaccus, Alcuin","m","730","804","Musikdokumentar","Abt#Gelehrter#Lehrer#Schulleiter#Bibliothekar","Aachen#Frankfurt/Main"}
			};
	}
	
}
